/** Answer → clue. Plain, unambiguous clues suitable for all ages. */
export const CLUES: [answer: string, clue: string][] = [
  ['apple', 'Fruit that keeps the doctor away'],
  ['ocean', 'Very large body of salt water'],
  ['tiger', 'Striped big cat'],
  ['piano', 'Keyboard instrument with 88 keys'],
  ['bread', 'Baked loaf made from flour'],
  ['cloud', 'White or grey mass floating in the sky'],
  ['river', 'Flowing body of fresh water'],
  ['chair', 'Seat with a back and four legs'],
  ['clock', 'Device that shows the time'],
  ['honey', 'Sweet food made by bees'],
  ['earth', 'Our home planet'],
  ['moon', 'Earth’s natural satellite'],
  ['star', 'The Sun is one'],
  ['sun', 'Star at the centre of our solar system'],
  ['rain', 'Water falling from clouds'],
  ['snow', 'Frozen flakes that fall in winter'],
  ['wind', 'Moving air'],
  ['tree', 'Tall plant with a trunk'],
  ['leaf', 'Green part of a plant that uses sunlight'],
  ['rose', 'Thorny flower, often red'],
  ['lion', 'King of the jungle'],
  ['bear', 'Large furry animal that may hibernate'],
  ['owl', 'Night bird that hoots'],
  ['cat', 'Pet that purrs'],
  ['dog', 'Pet that barks'],
  ['cow', 'Farm animal that gives milk'],
  ['pig', 'Farm animal that oinks'],
  ['hen', 'Female chicken'],
  ['bee', 'Insect that makes honey'],
  ['ant', 'Tiny insect that lives in a colony'],
  ['frog', 'Green amphibian that croaks'],
  ['duck', 'Bird that quacks'],
  ['horse', 'Animal you can ride that neighs'],
  ['sheep', 'Farm animal that gives wool'],
  ['whale', 'Largest mammal in the sea'],
  ['shark', 'Ocean predator with rows of teeth'],
  ['zebra', 'Striped African horse relative'],
  ['camel', 'Desert animal with humps'],
  ['snake', 'Legless reptile'],
  ['eagle', 'Large bird of prey'],
  ['mouse', 'Small rodent, or a computer pointer'],
  ['train', 'It runs on rails'],
  ['plane', 'It flies with wings and engines'],
  ['boat', 'Small vessel for water'],
  ['bus', 'Large vehicle for many passengers'],
  ['car', 'Four-wheeled road vehicle'],
  ['bike', 'Two-wheeled vehicle you pedal'],
  ['road', 'Paved way for vehicles'],
  ['bridge', 'Structure that crosses a river'],
  ['house', 'Building people live in'],
  ['door', 'You open it to enter a room'],
  ['window', 'Glass opening in a wall'],
  ['roof', 'Top covering of a building'],
  ['bed', 'Furniture for sleeping'],
  ['lamp', 'Device that gives light'],
  ['table', 'Furniture with a flat top and legs'],
  ['spoon', 'Utensil for soup'],
  ['fork', 'Utensil with prongs'],
  ['knife', 'Utensil with a blade'],
  ['plate', 'Flat dish for food'],
  ['cup', 'Small drinking vessel with a handle'],
  ['egg', 'Laid by a hen'],
  ['milk', 'White drink from cows'],
  ['cheese', 'Food made from curdled milk'],
  ['rice', 'Grain eaten across Asia'],
  ['pasta', 'Italian food like spaghetti'],
  ['pizza', 'Flat dough with toppings, baked'],
  ['soup', 'Liquid dish eaten with a spoon'],
  ['salt', 'White seasoning from the sea'],
  ['sugar', 'Sweet white crystals'],
  ['lemon', 'Sour yellow citrus fruit'],
  ['grape', 'Fruit used to make raisins'],
  ['peach', 'Fuzzy stone fruit'],
  ['melon', 'Large juicy fruit with many seeds'],
  ['corn', 'Yellow grain on a cob'],
  ['bean', 'Seed in a pod, like a kidney or green one'],
  ['carrot', 'Orange root vegetable'],
  ['onion', 'Layered vegetable that can make you cry'],
  ['book', 'Pages bound together to read'],
  ['pen', 'Writing tool with ink'],
  ['paper', 'Sheet you write on'],
  ['school', 'Place where children learn'],
  ['teacher', 'Person who helps you learn'],
  ['doctor', 'Person who treats the sick'],
  ['nurse', 'Hospital carer'],
  ['chef', 'Professional cook'],
  ['pilot', 'Person who flies a plane'],
  ['farmer', 'Person who grows crops'],
  ['king', 'Male ruler of a kingdom'],
  ['queen', 'Female ruler of a kingdom'],
  ['castle', 'Fortified home of a monarch'],
  ['music', 'Art made of sound and rhythm'],
  ['song', 'Music with words'],
  ['drum', 'Instrument you hit with sticks'],
  ['guitar', 'Instrument with six strings'],
  ['dance', 'Move to music'],
  ['movie', 'Film shown in a cinema'],
  ['game', 'Something played for fun'],
  ['ball', 'Round object used in many sports'],
  ['goal', 'What a football team scores'],
  ['team', 'Group playing together'],
  ['race', 'Contest of speed'],
  ['swim', 'Move through water'],
  ['run', 'Move fast on foot'],
  ['jump', 'Push off the ground into the air'],
  ['smile', 'Happy expression'],
  ['laugh', 'Sound made when something is funny'],
  ['happy', 'Feeling joy'],
  ['angry', 'Feeling cross'],
  ['brave', 'Showing courage'],
  ['quiet', 'Making little noise'],
  ['cold', 'Low in temperature'],
  ['hot', 'High in temperature'],
  ['fast', 'Quick'],
  ['slow', 'Not quick'],
  ['big', 'Large'],
  ['tiny', 'Very small'],
  ['red', 'Colour of a ripe tomato'],
  ['blue', 'Colour of a clear sky'],
  ['green', 'Colour of grass'],
  ['black', 'Colour of the night sky'],
  ['white', 'Colour of fresh snow'],
  ['gold', 'Precious yellow metal'],
  ['iron', 'Metal with the symbol Fe'],
  ['stone', 'Hard piece of rock'],
  ['sand', 'Tiny grains on a beach'],
  ['beach', 'Sandy shore by the sea'],
  ['island', 'Land surrounded by water'],
  ['hill', 'Small mountain'],
  ['lake', 'Body of water surrounded by land'],
  ['forest', 'Large area covered with trees'],
  ['desert', 'Very dry, sandy region'],
  ['winter', 'Coldest season'],
  ['summer', 'Warmest season'],
  ['spring', 'Season when flowers bloom'],
  ['week', 'Seven days'],
  ['year', 'Twelve months'],
  ['hour', 'Sixty minutes'],
  ['night', 'Dark part of the day'],
  ['morning', 'Early part of the day'],
  ['friend', 'Person you like and trust'],
  ['family', 'Parents and their children'],
  ['baby', 'Very young child'],
  ['hand', 'Part of the arm with fingers'],
  ['foot', 'You stand on it'],
  ['eye', 'You see with it'],
  ['ear', 'You hear with it'],
  ['nose', 'You smell with it'],
  ['heart', 'Organ that pumps blood'],
  ['brain', 'Organ you think with'],
  ['tooth', 'You chew with it'],
  ['map', 'Drawing that shows places'],
  ['key', 'It opens a lock'],
  ['gift', 'Present'],
  ['party', 'Celebration with friends'],
  ['cake', 'Sweet baked treat for birthdays'],
  ['candle', 'Wax stick with a wick'],
  ['robot', 'Machine that can do tasks automatically'],
  ['rocket', 'Vehicle that travels into space'],
  ['planet', 'Mars or Venus, for example'],
  ['magnet', 'It attracts iron'],
  ['atom', 'Tiny building block of matter'],
  ['oxygen', 'Gas we need to breathe'],
  ['water', 'H2O'],
  ['ice', 'Frozen water'],
  ['fire', 'Flames and heat'],
  ['light', 'What lets us see'],
];
