import type { AchievementDefinition } from '@/types';

/** Platform-wide achievements that are not tied to a single game. */
export const GLOBAL_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'global.first-game',
    gameId: null,
    name: 'First Game',
    description: 'Play your very first game.',
    target: 1,
    icon: '🎮',
    coins: 10,
  },
  {
    id: 'global.play-5',
    gameId: null,
    name: 'Getting Started',
    description: 'Play 5 games.',
    target: 5,
    icon: '🕹️',
    coins: 15,
  },
  {
    id: 'global.play-10',
    gameId: null,
    name: 'Warmed Up',
    description: 'Play 10 games.',
    target: 10,
    icon: '🔥',
    coins: 20,
  },
  {
    id: 'global.play-25',
    gameId: null,
    name: 'Regular Player',
    description: 'Play 25 games.',
    target: 25,
    icon: '⭐',
    coins: 30,
  },
  {
    id: 'global.play-50',
    gameId: null,
    name: 'Arcade Veteran',
    description: 'Play 50 games.',
    target: 50,
    icon: '🏅',
    coins: 50,
  },
  {
    id: 'global.play-100',
    gameId: null,
    name: 'Century',
    description: 'Play 100 games.',
    target: 100,
    icon: '💯',
    coins: 100,
  },
  {
    id: 'global.every-category',
    gameId: null,
    name: 'Explorer',
    description: 'Play a game from every category.',
    target: 13,
    icon: '🧭',
    coins: 75,
  },
  {
    id: 'global.first-win',
    gameId: null,
    name: 'Winner',
    description: 'Win your first game.',
    target: 1,
    icon: '🥇',
    coins: 15,
  },
  {
    id: 'global.first-record',
    gameId: null,
    name: 'Record Breaker',
    description: 'Beat one of your own high scores.',
    target: 1,
    icon: '📈',
    coins: 20,
  },
  {
    id: 'global.score-master',
    gameId: null,
    name: 'Score Master',
    description: 'Set high scores in 10 different games.',
    target: 10,
    icon: '🎯',
    coins: 60,
  },
  {
    id: 'global.puzzle-beginner',
    gameId: null,
    name: 'Puzzle Beginner',
    description: 'Play 3 puzzle games.',
    target: 3,
    icon: '🧩',
    coins: 15,
  },
  {
    id: 'global.puzzle-master',
    gameId: null,
    name: 'Puzzle Master',
    description: 'Play 15 puzzle games.',
    target: 15,
    icon: '🧠',
    coins: 50,
  },
  {
    id: 'global.arcade-fan',
    gameId: null,
    name: 'Arcade Fan',
    description: 'Play 10 arcade games.',
    target: 10,
    icon: '👾',
    coins: 40,
  },
  {
    id: 'global.board-fan',
    gameId: null,
    name: 'Board Game Fan',
    description: 'Play 8 board games.',
    target: 8,
    icon: '♟️',
    coins: 40,
  },
  {
    id: 'global.sports-fan',
    gameId: null,
    name: 'Sports Fan',
    description: 'Play 8 sports games.',
    target: 8,
    icon: '🏀',
    coins: 40,
  },
  {
    id: 'global.card-shark',
    gameId: null,
    name: 'Card Shark',
    description: 'Play 8 card games.',
    target: 8,
    icon: '🃏',
    coins: 40,
  },
  {
    id: 'global.achievements-10',
    gameId: null,
    name: 'Collector',
    description: 'Unlock 10 achievements.',
    target: 10,
    icon: '🏆',
    coins: 25,
  },
  {
    id: 'global.achievements-25',
    gameId: null,
    name: 'Trophy Hunter',
    description: 'Unlock 25 achievements.',
    target: 25,
    icon: '🏆',
    coins: 50,
  },
  {
    id: 'global.achievements-50',
    gameId: null,
    name: 'Completionist',
    description: 'Unlock 50 achievements.',
    target: 50,
    icon: '👑',
    coins: 100,
  },
  {
    id: 'global.favorite-5',
    gameId: null,
    name: 'Curator',
    description: 'Add 5 games to your favorites.',
    target: 5,
    icon: '❤️',
    coins: 15,
  },
  {
    id: 'global.daily-1',
    gameId: null,
    name: 'Daily Player',
    description: 'Complete a daily challenge.',
    target: 1,
    icon: '📅',
    coins: 25,
  },
  {
    id: 'global.daily-7',
    gameId: null,
    name: 'Streak Keeper',
    description: 'Complete 7 daily challenges.',
    target: 7,
    icon: '🗓️',
    coins: 75,
  },
  {
    id: 'global.coins-500',
    gameId: null,
    name: 'Coin Collector',
    description: 'Earn 500 coins in total.',
    target: 500,
    icon: '🪙',
    coins: 50,
  },
  {
    id: 'global.playtime-1h',
    gameId: null,
    name: 'One More Round',
    description: 'Play for a total of one hour.',
    target: 3_600_000,
    icon: '⏱️',
    coins: 40,
  },
];
