// Generated by scripts/gen-puzzle-levels.ts. Original layouts; "moves" is the exact minimum.
export interface UnblockLevel {
  level: string;
  moves: number;
}

export const LEVEL_PACKS: Record<'easy' | 'normal' | 'hard', UnblockLevel[]> = {
  "easy": [
    {
      "level": ".f.....fc..baacd.bijjdkkihhh..ieegg.",
      "moves": 4
    },
    {
      "level": "bf...dbf.iidaa..cgjh..cgjh...g.h..ee",
      "moves": 4
    },
    {
      "level": ".ghh...gfff.aa..dc.ibbdc.i.ee.......",
      "moves": 4
    },
    {
      "level": "..ggg.....ce..aace.ff.i...bbih.dd..h",
      "moves": 4
    },
    {
      "level": "bee.ccbkkiiiaagj.fhdgj.fhd.....dlll.",
      "moves": 4
    },
    {
      "level": ".dee...df...aafc..gg.chh...bbb......",
      "moves": 4
    },
    {
      "level": ".b.....b...haa.efh.ggef..ii....ddcc.",
      "moves": 4
    },
    {
      "level": "...ggghhheccaafe....fdd...bb........",
      "moves": 5
    },
    {
      "level": ".d.ffi.d.hhi.aa.gj....gj.cc.e.bbb.e.",
      "moves": 5
    },
    {
      "level": "g.ee..gffhddaabh..llbjj.ccb...iikkk.",
      "moves": 5
    },
    {
      "level": "...dddb.gghcbaaehc...eff............",
      "moves": 5
    },
    {
      "level": "...cccggb..eaab..e..iihh..dd..ff....",
      "moves": 5
    },
    {
      "level": "d..gggdbbe..daae.c.....c.h.ff..h....",
      "moves": 5
    },
    {
      "level": "..ii...hhdddaaj..e..jbbe.fccc..fgg..",
      "moves": 5
    },
    {
      "level": "fhmm..fhii.caaegjcbdegjcbdlk..bdlk..",
      "moves": 7
    },
    {
      "level": ".h..cc.hi.ddaai.embbffeml..jjglkkk.g",
      "moves": 7
    },
    {
      "level": "....d...bbd..aaiehfffieh.jjje...ggcc",
      "moves": 7
    },
    {
      "level": ".cb.kk.cbee.aab.idhhggid...jjd..ff..",
      "moves": 7
    },
    {
      "level": ".e.ggg.e.iid.eaabdcc..bd.hh.f.....f.",
      "moves": 7
    },
    {
      "level": ".dddcc.ee..f..aaifggb.if..b.hh..b...",
      "moves": 8
    }
  ],
  "normal": [
    {
      "level": "ffddd.ee..g.aa..g.cbb.jjc..hh.c...ii",
      "moves": 10
    },
    {
      "level": "fffi..bc.ihhbc.aagbdd..g....kj.eeekj",
      "moves": 10
    },
    {
      "level": "jhi...jhifffgaabd.g..bd.g...c.eee.c.",
      "moves": 10
    },
    {
      "level": "h..mmfh.ddeflaaceflb.cjjkb.i..k..igg",
      "moves": 10
    },
    {
      "level": "..geeeddg....kaali.k.flijh.f.ijhbbcc",
      "moves": 10
    },
    {
      "level": "........ccb..aaebf.ddebf..giif..ghh.",
      "moves": 10
    },
    {
      "level": "...jjd..ccfd..aafdiihhf.b.e...b.egg.",
      "moves": 11
    },
    {
      "level": ".bjj...beeecaafg.c..fg..hhhii.dd....",
      "moves": 11
    },
    {
      "level": "..gg..eeejdhbaajdhb..j..ifc...ifckkk",
      "moves": 11
    },
    {
      "level": "d.bbb.d..ciiaa.cgk.mmhgkf..hjef.llje",
      "moves": 11
    },
    {
      "level": "..ibdd..ib...aabh.....hc.ggffc.eee..",
      "moves": 11
    },
    {
      "level": "..fiii..fe...aae.....eccddhhj.ggbbj.",
      "moves": 11
    },
    {
      "level": "bff.d.bcc.d.aai.d..hi.gg.h...e.hjjje",
      "moves": 13
    },
    {
      "level": "lddd.ilmheeijmhaaijffkc...bkc...bkgg",
      "moves": 13
    },
    {
      "level": ".elljj.e.bkkaa.bghimmbghi.ddchifffc.",
      "moves": 13
    },
    {
      "level": "hdbbiihdjgg.aaj.ek..j.ek....lkffccl.",
      "moves": 14
    },
    {
      "level": "ggiffkddi.hkeaamhcebbmlcej.mlc.j....",
      "moves": 15
    },
    {
      "level": "b...ddbg..fcbgaafciie.fc..ehhh......",
      "moves": 15
    },
    {
      "level": ".h.iimkhddcmkaagc.beeg..b.fjll..fj..",
      "moves": 16
    },
    {
      "level": "..bgg...be..aabe.d...fidhccfidh.....",
      "moves": 16
    }
  ],
  "hard": [
    {
      "level": "...bee...bh...aah.ccddh..jggkk.jffii",
      "moves": 17
    },
    {
      "level": "kkiif.g...fbg.eaabccejjb...dll...dhh",
      "moves": 18
    },
    {
      "level": ".bbbih..eeihaak..jffk..jlggccjl..ddd",
      "moves": 18
    },
    {
      "level": "igccc.igbb..jaak..jmlkddjmlffh..leeh",
      "moves": 18
    },
    {
      "level": "ccck....gkllaag..fbbjj.fihh.eei..dd.",
      "moves": 18
    },
    {
      "level": ".kkkgjeellgjaad.gj..dhbbc..h..cffii.",
      "moves": 18
    },
    {
      "level": ".hhbcc...bkkjaabeljiffel.ig..mddg..m",
      "moves": 18
    },
    {
      "level": "hhjjgd.iffgd.imaadbbml.....lee.kkccc",
      "moves": 18
    },
    {
      "level": "ldc...ldc.hf.daahfgbbe.fg.jeiikkjmm.",
      "moves": 19
    },
    {
      "level": "bbmmg.d.kkgfd..aafdllccf.eehnn.jjhii",
      "moves": 19
    },
    {
      "level": "hb.jj.hb...dh.aagdcckegdi.kellifff..",
      "moves": 19
    },
    {
      "level": "...c....hc..aahfeb.jjfeb.gddei.gkk.i",
      "moves": 19
    },
    {
      "level": ".hhccf...kbf.aakb.ijggllijm..eddm..e",
      "moves": 20
    },
    {
      "level": ".mmnhhkkin.f.eiaaf.ejddcl.j.bcl.ggbc",
      "moves": 20
    },
    {
      "level": "d.c.kkd.c.iiaac..b.....bfffhjeggghje",
      "moves": 20
    },
    {
      "level": ".gcc.i.ghlliaahfdj..efdjk.eb..kmmb..",
      "moves": 21
    },
    {
      "level": "gg.j..cccj..lh.aaelh..iebdd.iebkkfff",
      "moves": 22
    },
    {
      "level": "eedii...dff.aadg..h..gkkhbbg.lccjj.l",
      "moves": 24
    },
    {
      "level": "k.fbbjk.f..jaaf.li.ehhlime.gddmccg..",
      "moves": 26
    },
    {
      "level": "..kiii..k.lcaae.lcjjeddcf..hbbfggh..",
      "moves": 32
    }
  ]
};
