/**
 * Logic Grid: an "Einstein" deduction puzzle. Several people each have one
 * item from every category. Clues narrow the possibilities until only one
 * assignment remains.
 *
 * A candidate solution assigns, for every category except names, a
 * permutation: perm[c][person] = item. Puzzles are generated by picking a
 * secret solution, adding random true clues until it is the only candidate,
 * then removing clues that turn out to be redundant.
 */
export type Level = 'easy' | 'normal' | 'hard';

export interface Category {
  name: string;
  items: string[];
  /** Phrase for "the person with this item", {} replaced by the item. */
  phrase: string;
  ordered?: boolean;
}

const NAMES = ['Ava', 'Ben', 'Cleo', 'Dev', 'Esme'];
const POOL: Category[] = [
  { name: 'Colour', items: ['red', 'blue', 'green', 'yellow', 'purple'], phrase: 'the {} fan' },
  { name: 'Pet', items: ['cat', 'dog', 'fish', 'parrot', 'rabbit'], phrase: 'the {} owner' },
  { name: 'Drink', items: ['tea', 'coffee', 'juice', 'milk', 'cocoa'], phrase: 'the {} drinker' },
  { name: 'Hobby', items: ['chess', 'painting', 'cycling', 'baking', 'singing'], phrase: 'the {} lover' },
];
const AGE: Category = { name: 'Age', items: ['20', '30', '40', '50', '60'], phrase: 'the {}-year-old', ordered: true };

const SETTINGS: Record<Level, { n: number; plain: number; age: boolean }> = {
  easy: { n: 3, plain: 2, age: false },
  normal: { n: 4, plain: 1, age: true },
  hard: { n: 5, plain: 1, age: true },
};

export type Perms = number[][];
export interface Ref {
  cat: number;
  item: number;
}

export type Clue =
  | { kind: 'same'; a: Ref; b: Ref }
  | { kind: 'diff'; a: Ref; b: Ref }
  | { kind: 'older'; a: Ref; b: Ref }
  | { kind: 'either'; a: Ref; b: Ref; c: Ref };

export interface Puzzle {
  categories: Category[];
  n: number;
  /** solution[c][person] = item; category 0 is the identity (names). */
  solution: Perms;
  clues: Clue[];
}

const personOf = (p: Perms, r: Ref) => (r.cat === 0 ? r.item : p[r.cat].indexOf(r.item));

export function holds(p: Perms, clue: Clue, ageCat: number): boolean {
  const a = personOf(p, clue.a);
  const b = personOf(p, clue.b);
  switch (clue.kind) {
    case 'same':
      return a === b;
    case 'diff':
      return a !== b;
    case 'older':
      return a !== b && p[ageCat][a] > p[ageCat][b];
    case 'either': {
      const c = personOf(p, clue.c);
      return (a === b) !== (a === c);
    }
  }
}

function permutations(n: number): number[][] {
  if (n === 1) return [[0]];
  const out: number[][] = [];
  for (const p of permutations(n - 1)) for (let i = 0; i <= p.length; i++) out.push([...p.slice(0, i), n - 1, ...p.slice(i)]);
  return out;
}

/** Every complete assignment for n people and k categories (names fixed). */
export function allCandidates(n: number, k: number): Perms[] {
  const perms = permutations(n);
  let out: Perms[] = [[Array.from({ length: n }, (_, i) => i)]];
  for (let c = 1; c < k; c++) out = out.flatMap((partial) => perms.map((p) => [...partial, p]));
  return out;
}

const shuffle = <T,>(a: T[], random: () => number) => {
  const r = [...a];
  for (let i = r.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [r[i], r[j]] = [r[j], r[i]];
  }
  return r;
};

function randomRef(k: number, n: number, random: () => number, except: number[] = []): Ref {
  let cat = 0;
  do cat = Math.floor(random() * k);
  while (except.includes(cat));
  return { cat, item: Math.floor(random() * n) };
}

/** A random clue that is true of the solution. */
function randomClue(sol: Perms, k: number, n: number, ageCat: number, random: () => number): Clue | null {
  const r = random();
  if (ageCat >= 0 && r < 0.25) {
    const a = randomRef(k, n, random, [ageCat]);
    const b = randomRef(k, n, random, [ageCat]);
    const clue: Clue = { kind: 'older', a, b };
    return holds(sol, clue, ageCat) ? clue : null;
  }
  const a = randomRef(k, n, random);
  const b = randomRef(k, n, random, [a.cat]);
  if (r < 0.55) {
    const clue: Clue = { kind: 'same', a, b };
    return holds(sol, clue, ageCat) ? clue : null;
  }
  if (r < 0.85) {
    const clue: Clue = { kind: 'diff', a, b };
    return holds(sol, clue, ageCat) ? clue : null;
  }
  const c: Ref = { cat: b.cat, item: Math.floor(random() * n) };
  if (c.item === b.item) return null;
  const clue: Clue = { kind: 'either', a, b, c };
  return holds(sol, clue, ageCat) ? clue : null;
}

export function generate(level: Level, random: () => number): Puzzle {
  const { n, plain, age } = SETTINGS[level];
  const names: Category = { name: 'Name', items: shuffle(NAMES, random).slice(0, n), phrase: '{}' };
  const cats = shuffle(POOL, random)
    .slice(0, plain)
    .map((c) => ({ ...c, items: shuffle(c.items, random).slice(0, n) }));
  const categories = [names, ...cats, ...(age ? [{ ...AGE, items: AGE.items.slice(0, n) }] : [])];
  const k = categories.length;
  const ageCat = age ? k - 1 : -1;
  const all = allCandidates(n, k);
  const solution = all[Math.floor(random() * all.length)];
  let alive = all;
  const clues: Clue[] = [];
  for (let guard = 0; alive.length > 1 && guard < 2000; guard++) {
    const clue = randomClue(solution, k, n, ageCat, random);
    if (!clue) continue;
    const next = alive.filter((p) => holds(p, clue, ageCat));
    // Only keep clues that rule something out.
    if (next.length < alive.length) {
      clues.push(clue);
      alive = next;
    }
  }
  // Drop clues that are implied by the others.
  for (let i = clues.length - 1; i >= 0; i--) {
    const rest = clues.filter((_, j) => j !== i);
    if (all.filter((p) => rest.every((c) => holds(p, c, ageCat))).length === 1) clues.splice(i, 1);
  }
  return { categories, n, solution, clues: shuffle(clues, random) };
}

export function countSolutions(p: Puzzle): number {
  const ageCat = p.categories.findIndex((c) => c.ordered);
  return allCandidates(p.n, p.categories.length).filter((c) => p.clues.every((cl) => holds(c, cl, ageCat))).length;
}

const refText = (cats: Category[], r: Ref) => cats[r.cat].phrase.replace('{}', cats[r.cat].items[r.item]);
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export function clueText(cats: Category[], clue: Clue): string {
  const a = refText(cats, clue.a);
  const b = refText(cats, clue.b);
  switch (clue.kind) {
    case 'same':
      return `${cap(a)} is ${b}.`;
    case 'diff':
      return `${cap(a)} is not ${b}.`;
    case 'older':
      return `${cap(a)} is older than ${b}.`;
    case 'either':
      return `${cap(a)} is either ${b} or ${refText(cats, clue.c)}.`;
  }
}

/** Marks: for each person, category (≥1) and item: 0 blank, 1 ✗, 2 ✓. */
export type Marks = number[][][];

export const emptyMarks = (n: number, k: number): Marks =>
  Array.from({ length: n }, () => Array.from({ length: k }, () => Array(n).fill(0)));

/** Solved when every person has the correct single ✓ in every category. */
export function marksSolve(p: Puzzle, marks: Marks): boolean {
  for (let person = 0; person < p.n; person++) {
    for (let c = 1; c < p.categories.length; c++) {
      const ticks = marks[person][c].flatMap((m, i) => (m === 2 ? [i] : []));
      if (ticks.length !== 1 || ticks[0] !== p.solution[c][person]) return false;
    }
  }
  return true;
}
