import type { Rng } from '@/utils/random';
import type { DifficultySetting } from '@/types';
import { drawFromBank } from '../_shared/quiz/engine';
import type { BankItem, QuizQuestion } from '../_shared/quiz/engine';

export const BANK: BankItem[] = [
  {
    prompt: 'What is the largest ocean on Earth?',
    correct: 'Pacific Ocean',
    wrong: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
    level: 1,
  },
  { prompt: 'How many continents are there?', correct: '7', wrong: ['5', '6', '8'], level: 1 },
  {
    prompt: 'What is the highest mountain above sea level?',
    correct: 'Mount Everest',
    wrong: ['K2', 'Kangchenjunga', 'Mont Blanc'],
    level: 1,
  },
  {
    prompt: 'Which is the largest country by area?',
    correct: 'Russia',
    wrong: ['Canada', 'China', 'United States'],
    level: 1,
  },
  {
    prompt: 'Which is the smallest country in the world?',
    correct: 'Vatican City',
    wrong: ['Monaco', 'San Marino', 'Liechtenstein'],
    level: 1,
  },
  {
    prompt: 'Which continent is Egypt in?',
    correct: 'Africa',
    wrong: ['Asia', 'Europe', 'South America'],
    level: 1,
  },
  {
    prompt: 'Which continent is Brazil in?',
    correct: 'South America',
    wrong: ['North America', 'Africa', 'Europe'],
    level: 1,
  },
  {
    prompt: 'The Sahara is the largest hot desert. Which continent is it on?',
    correct: 'Africa',
    wrong: ['Asia', 'Australia', 'South America'],
    level: 1,
  },
  {
    prompt: 'Which country has the largest population?',
    correct: 'India',
    wrong: ['China', 'United States', 'Indonesia'],
    level: 2,
    explain: 'India overtook China as the most populous country in 2023.',
  },
  {
    prompt: 'Which river flows through Egypt?',
    correct: 'Nile',
    wrong: ['Amazon', 'Congo', 'Niger'],
    level: 1,
  },
  {
    prompt: 'Which river carries the most water in the world?',
    correct: 'Amazon',
    wrong: ['Nile', 'Yangtze', 'Mississippi'],
    level: 2,
  },
  {
    prompt: 'The Great Barrier Reef lies off the coast of which country?',
    correct: 'Australia',
    wrong: ['Indonesia', 'New Zealand', 'Philippines'],
    level: 1,
  },
  {
    prompt: 'Which mountain range separates Europe and Asia?',
    correct: 'Ural Mountains',
    wrong: ['Alps', 'Himalayas', 'Carpathians'],
    level: 3,
  },
  {
    prompt: 'Which mountain range includes Mount Everest?',
    correct: 'Himalayas',
    wrong: ['Andes', 'Rockies', 'Alps'],
    level: 1,
  },
  {
    prompt: 'What is the longest mountain range on land?',
    correct: 'Andes',
    wrong: ['Himalayas', 'Rocky Mountains', 'Alps'],
    level: 2,
  },
  {
    prompt: 'Which is the largest island in the world (not a continent)?',
    correct: 'Greenland',
    wrong: ['New Guinea', 'Borneo', 'Madagascar'],
    level: 2,
  },
  {
    prompt: 'What is the deepest known point in the ocean?',
    correct: 'Challenger Deep',
    wrong: ['Puerto Rico Trench', 'Java Trench', 'Tonga Trench'],
    level: 3,
    explain: 'It lies in the Mariana Trench in the western Pacific.',
  },
  {
    prompt: 'Which country has the most time zones (including overseas territories)?',
    correct: 'France',
    wrong: ['Russia', 'United States', 'China'],
    level: 3,
  },
  {
    prompt: 'Which is the largest lake by area?',
    correct: 'Caspian Sea',
    wrong: ['Lake Superior', 'Lake Victoria', 'Lake Baikal'],
    level: 2,
  },
  {
    prompt: 'Which is the deepest lake in the world?',
    correct: 'Lake Baikal',
    wrong: ['Lake Tanganyika', 'Caspian Sea', 'Lake Superior'],
    level: 3,
  },
  {
    prompt: 'Which line divides Earth into Northern and Southern Hemispheres?',
    correct: 'The Equator',
    wrong: ['Prime Meridian', 'Tropic of Cancer', 'Arctic Circle'],
    level: 1,
  },
  {
    prompt: 'The Prime Meridian passes through which city?',
    correct: 'London (Greenwich)',
    wrong: ['Paris', 'Madrid', 'Lisbon'],
    level: 2,
  },
  {
    prompt: 'Which country is shaped like a boot?',
    correct: 'Italy',
    wrong: ['Greece', 'Portugal', 'Chile'],
    level: 1,
  },
  {
    prompt: 'Which country is the long, thin one along the west coast of South America?',
    correct: 'Chile',
    wrong: ['Peru', 'Argentina', 'Ecuador'],
    level: 2,
  },
  {
    prompt: 'Which sea has water so salty that people float easily in it?',
    correct: 'Dead Sea',
    wrong: ['Red Sea', 'Black Sea', 'Baltic Sea'],
    level: 1,
  },
  {
    prompt: 'Which is the coldest continent?',
    correct: 'Antarctica',
    wrong: ['Europe', 'Asia', 'North America'],
    level: 1,
  },
  {
    prompt: 'Which continent has the most countries?',
    correct: 'Africa',
    wrong: ['Europe', 'Asia', 'South America'],
    level: 2,
  },
  {
    prompt: 'Which country has the most natural lakes?',
    correct: 'Canada',
    wrong: ['Finland', 'Russia', 'United States'],
    level: 3,
  },
  {
    prompt: 'Mount Kilimanjaro is in which country?',
    correct: 'Tanzania',
    wrong: ['Kenya', 'Uganda', 'Ethiopia'],
    level: 2,
  },
  {
    prompt: 'Which strait separates Europe from Africa?',
    correct: 'Strait of Gibraltar',
    wrong: ['Bosphorus', 'Strait of Hormuz', 'Bering Strait'],
    level: 2,
  },
  {
    prompt: 'Which strait separates Asia from North America?',
    correct: 'Bering Strait',
    wrong: ['Strait of Gibraltar', 'Strait of Malacca', 'Cook Strait'],
    level: 3,
  },
  {
    prompt: 'Which canal connects the Atlantic and Pacific Oceans?',
    correct: 'Panama Canal',
    wrong: ['Suez Canal', 'Kiel Canal', 'Corinth Canal'],
    level: 1,
  },
  {
    prompt: 'Which canal connects the Mediterranean Sea and the Red Sea?',
    correct: 'Suez Canal',
    wrong: ['Panama Canal', 'Kiel Canal', 'Erie Canal'],
    level: 2,
  },
  {
    prompt: 'Which country has the longest coastline?',
    correct: 'Canada',
    wrong: ['Russia', 'Australia', 'Norway'],
    level: 3,
  },
  {
    prompt: 'Which is the tallest waterfall in the world?',
    correct: 'Angel Falls',
    wrong: ['Niagara Falls', 'Victoria Falls', 'Iguazu Falls'],
    level: 2,
    explain: 'Angel Falls in Venezuela drops about 979 metres.',
  },
  {
    prompt: 'Which ocean lies between Africa and Australia?',
    correct: 'Indian Ocean',
    wrong: ['Pacific Ocean', 'Atlantic Ocean', 'Southern Ocean'],
    level: 1,
  },
  {
    prompt: 'In which country would you find the ancient city of Machu Picchu?',
    correct: 'Peru',
    wrong: ['Mexico', 'Bolivia', 'Chile'],
    level: 2,
  },
  {
    prompt: 'Which river runs through Paris?',
    correct: 'Seine',
    wrong: ['Thames', 'Danube', 'Rhine'],
    level: 2,
  },
  {
    prompt: 'Which river runs through London?',
    correct: 'Thames',
    wrong: ['Seine', 'Severn', 'Tyne'],
    level: 1,
  },
  {
    prompt: 'The Danube flows into which sea?',
    correct: 'Black Sea',
    wrong: ['North Sea', 'Mediterranean Sea', 'Baltic Sea'],
    level: 3,
  },
  {
    prompt: 'Which desert covers much of southern Mongolia and northern China?',
    correct: 'Gobi',
    wrong: ['Kalahari', 'Atacama', 'Namib'],
    level: 2,
  },
  {
    prompt: 'Which desert is one of the driest places on Earth, in northern Chile?',
    correct: 'Atacama',
    wrong: ['Gobi', 'Mojave', 'Sahara'],
    level: 3,
  },
  {
    prompt: 'Which U.S. state is made up entirely of islands?',
    correct: 'Hawaii',
    wrong: ['Alaska', 'Florida', 'Rhode Island'],
    level: 1,
  },
  {
    prompt: 'Which country is both in Europe and Asia and has Istanbul as its largest city?',
    correct: 'Turkey',
    wrong: ['Greece', 'Russia', 'Georgia'],
    level: 2,
  },
  {
    prompt: 'Which country has the city of Timbuktu?',
    correct: 'Mali',
    wrong: ['Niger', 'Chad', 'Senegal'],
    level: 3,
  },
  {
    prompt: 'Which island country lies off the southeast coast of Africa?',
    correct: 'Madagascar',
    wrong: ['Sri Lanka', 'Cuba', 'Iceland'],
    level: 1,
  },
  {
    prompt: 'Iceland sits on which ocean ridge?',
    correct: 'Mid-Atlantic Ridge',
    wrong: ['East Pacific Rise', 'Carlsberg Ridge', 'Southwest Indian Ridge'],
    level: 3,
  },
  {
    prompt: 'Which country has the most active volcanoes?',
    correct: 'Indonesia',
    wrong: ['Japan', 'Italy', 'Iceland'],
    level: 3,
  },
];

export const makeQuestions = (rng: Rng, d: DifficultySetting): QuizQuestion[] =>
  drawFromBank(BANK, rng, d, 10);
