/**
 * Original 16 × 16 pixel sprites for the creative games. Each row is a
 * string; every character is a palette key ('.' is empty).
 */
export interface Sprite {
  id: string;
  name: string;
  palette: Record<string, string>;
  rows: string[];
}

export const SPRITES: Sprite[] = [
  {
    id: 'heart',
    name: 'Heart',
    palette: { r: '#e11d48', p: '#fb7185', w: '#ffe4e6', k: '#4c0519' },
    rows: [
      '................',
      '................',
      '...kkk....kkk...',
      '..krrrk..krrrk..',
      '.krpwrrkkrrrrrk.',
      '.krwprrrrrrrrrk.',
      '.krprrrrrrrrrrk.',
      '.krrrrrrrrrrrrk.',
      '..krrrrrrrrrrk..',
      '...krrrrrrrrk...',
      '....krrrrrrk....',
      '.....krrrrk.....',
      '......krrk......',
      '.......kk.......',
      '................',
      '................',
    ],
  },
  {
    id: 'mushroom',
    name: 'Mushroom',
    palette: { r: '#dc2626', w: '#fff7ed', s: '#fde68a', k: '#3f1d0b', e: '#1f2937' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkrrwwrrkk...',
      '..krrrwwwwrrrk..',
      '.krwwrrwwrrwwrk.',
      '.krwwrrrrrrwwrk.',
      'krrrrrwwwwrrrrrk',
      'krrrrwwwwwwrrrrk',
      'kkkkkkkkkkkkkkkk',
      '....kssssssk....',
      '....ksesseesk...',
      '....ksesseesk...',
      '....kssssssk....',
      '....kssssssk....',
      '.....kkkkkk.....',
      '................',
    ],
  },
  {
    id: 'cat',
    name: 'Cat',
    palette: { o: '#f59e0b', y: '#fcd34d', k: '#1f2937', p: '#f9a8d4', w: '#ffffff' },
    rows: [
      '................',
      '..k..........k..',
      '.kok........kok.',
      '.kook......kook.',
      '.koookkkkkkoook.',
      '.koooooooooooook',
      'kooooooooooooook',
      'kookwkoooookwkok',
      'kookkkoooookkkok',
      'kooooooppooooook',
      'koyyyookkooyyyok',
      'koyyyyyooyyyyyok',
      '.kyyyyyyyyyyyyk.',
      '..kyyyyyyyyyyk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  {
    id: 'house',
    name: 'House',
    palette: { r: '#b91c1c', w: '#fef3c7', b: '#78350f', g: '#38bdf8', k: '#1f2937', c: '#9ca3af' },
    rows: [
      '...........cc...',
      '.......k...cc...',
      '......krk..cc...',
      '.....krrrk.cc...',
      '....krrrrrkcc...',
      '...krrrrrrrkc...',
      '..krrrrrrrrrk...',
      '.krrrrrrrrrrrk..',
      'kkkkkkkkkkkkkkk.',
      '.kwwwwwwwwwwwk..',
      '.kwggwwwwwggwk..',
      '.kwggwwbbwggwk..',
      '.kwwwwwbbwwwwk..',
      '.kwwwwwbbwwwwk..',
      '.kkkkkkkkkkkkk..',
      '................',
    ],
  },
  {
    id: 'tree',
    name: 'Tree',
    palette: { g: '#16a34a', l: '#4ade80', d: '#14532d', b: '#78350f', k: '#1f2937' },
    rows: [
      '......kkkk......',
      '....kkllggkk....',
      '...kllggggggk...',
      '..klgggggggggk..',
      '.klggggdggggggk.',
      '.kgggggggggdggk.',
      'klgggdggggggggk.',
      'kggggggggggggdk.',
      '.kgggggdgggggk..',
      '..kkggggggggk...',
      '....kkkbbkkk....',
      '......kbbk......',
      '......kbbk......',
      '......kbbk......',
      '....kkbbbbkk....',
      '................',
    ],
  },
  {
    id: 'fish',
    name: 'Fish',
    palette: { b: '#0ea5e9', l: '#7dd3fc', y: '#facc15', k: '#0f172a', w: '#ffffff' },
    rows: [
      '................',
      '................',
      '......kkkk......',
      '....kkbbbbkk....',
      '...kbbbbbbbbk.kk',
      '..kbwkbbbbbbbkbk',
      '.kbbkkbbbllbbbbk',
      '.kbbbbbbllllbbbk',
      '.kbbbbbbllllbbbk',
      '.kyybbbbbllbbbbk',
      '..kyybbbbbbbbkbk',
      '...kbbbbbbbbk.kk',
      '....kkbbbbkk....',
      '......kkkk......',
      '................',
      '................',
    ],
  },
  {
    id: 'rocket',
    name: 'Rocket',
    palette: { w: '#e5e7eb', r: '#ef4444', b: '#3b82f6', o: '#f97316', y: '#fde047', k: '#111827' },
    rows: [
      '.......kk.......',
      '......krrk......',
      '.....krrrrk.....',
      '.....kwwwwk.....',
      '....kwwbbwwk....',
      '....kwbbbbwk....',
      '....kwwbbwwk....',
      '....kwwwwwwk....',
      '....kwwwwwwk....',
      '...krkwwwwkrk...',
      '..krrkwwwwkrrk..',
      '..krrkkkkkkrrk..',
      '...kk.kook.kk...',
      '......kyyk......',
      '.......yy.......',
      '................',
    ],
  },
  {
    id: 'flower',
    name: 'Flower',
    palette: { p: '#ec4899', l: '#f9a8d4', y: '#facc15', g: '#22c55e', d: '#15803d', k: '#1f2937' },
    rows: [
      '......kkkk......',
      '.....kllllk.....',
      '..kkkkllllkkkk..',
      '.kllppkyykppllk.',
      '.klpppyyyyppplk.',
      '..kkppyyyyppkk..',
      '.kllppkyykppllk.',
      '.klpppkllkppplk.',
      '..kkkkllllkkkk..',
      '.....kllllk.....',
      '......kgk.......',
      '..kk..kgk..kk...',
      '..kgk.kgk.kgk...',
      '...kgkkgkkgk....',
      '....kddddddk....',
      '................',
    ],
  },
  {
    id: 'duck',
    name: 'Duck',
    palette: { y: '#facc15', o: '#f97316', k: '#1f2937', w: '#ffffff', b: '#38bdf8' },
    rows: [
      '................',
      '.....kkkk.......',
      '....kyyyyk......',
      '...kyywkyyk.....',
      '...kyykkyyk.....',
      '...kyyyyyykoo...',
      '....kyyyykoooo..',
      '.....kyyk.kkk...',
      '..kkkyyyykkk....',
      '.kyyyyyyyyyyk...',
      'kyyyyyyyyyyyyk..',
      'kyyykyyyyyyyyk..',
      '.kyyykkkkyyyk...',
      '..kkkyyyyykk....',
      'bbbbbkkkkkbbbbbb',
      'bbbbbbbbbbbbbbbb',
    ],
  },
  {
    id: 'sun',
    name: 'Sun',
    palette: { y: '#fde047', o: '#f59e0b', k: '#78350f', r: '#fb923c' },
    rows: [
      '.......o........',
      '..o....o....o...',
      '...o.......o....',
      '......kkkk......',
      '....kkyyyykk....',
      '...kyyyyyyyyk...',
      '...kykyyyykyk...',
      'oo.kyyyyyyyyk.oo',
      '...kyryyyyryk...',
      '...kyykkkkyyk...',
      '....kkyyyykk....',
      '......kkkk......',
      '...o.......o....',
      '..o....o....o...',
      '.......o........',
      '................',
    ],
  },
  {
    id: 'cherry',
    name: 'Cherries',
    palette: { r: '#dc2626', d: '#991b1b', w: '#fecaca', g: '#16a34a', b: '#78350f', k: '#1f2937' },
    rows: [
      '..........gg....',
      '.........gggg...',
      '........bggg....',
      '.......b.b......',
      '......b...b.....',
      '.....b.....b....',
      '....b.......b...',
      '...kkk.....kkk..',
      '..krwrk...krwrk.',
      '.krwrrrk.krwrrrk',
      '.krrrrrk.krrrrrk',
      '.krrrrdk.krrrrdk',
      '..krrdk...krrdk.',
      '...kkk.....kkk..',
      '................',
      '................',
    ],
  },
  {
    id: 'cup',
    name: 'Mug',
    palette: { b: '#2563eb', l: '#93c5fd', w: '#e5e7eb', c: '#78350f', k: '#0f172a' },
    rows: [
      '................',
      '....w..w..w.....',
      '.....w..w..w....',
      '....w..w..w.....',
      '................',
      '..kkkkkkkkkk....',
      '..kccccccccckk..',
      '..kbbbbbbbbbkbk.',
      '..kblbbbbbbbk.k.',
      '..kblbbbbbbbk.k.',
      '..kblbbbbbbbkbk.',
      '..kbbbbbbbbbkk..',
      '..kbbbbbbbbbk...',
      '...kbbbbbbbk....',
      '....kkkkkkk.....',
      '................',
    ],
  },
];

/** Hex colour of a sprite cell, or null if empty. */
export function cellColor(s: Sprite, x: number, y: number): string | null {
  const ch = s.rows[y]?.[x] ?? '.';
  return ch === '.' ? null : (s.palette[ch] ?? null);
}

export const SIZE = 16;
