// Generated by scripts/gen-registry.mjs — do not edit by hand.
/* eslint-disable */
import * as m0 from './aim-trainer/definition';
import * as m1 from './air-hockey/definition';
import * as m2 from './airport-manager/definition';
import * as m3 from './alien-defender/definition';
import * as m4 from './alien-invasion/definition';
import * as m5 from './alien-shooter/definition';
import * as m6 from './alphabet-game/definition';
import * as m7 from './anagram/definition';
import * as m8 from './archery/definition';
import * as m9 from './archery-challenge/definition';
import * as m10 from './army-strategy/definition';
import * as m11 from './asteroid-blaster/definition';
import * as m12 from './asteroid-defense/definition';
import * as m13 from './avoid-obstacles/definition';
import * as m14 from './baccarat/definition';
import * as m15 from './backgammon/definition';
import * as m16 from './balance-game/definition';
import * as m17 from './balance-puzzle/definition';
import * as m18 from './ball-bounce/definition';
import * as m19 from './ball-sort/definition';
import * as m20 from './baseball-batting/definition';
import * as m21 from './basketball-shot/definition';
import * as m22 from './battleship/definition';
import * as m23 from './bike-race/definition';
import * as m24 from './binary-puzzle/definition';
import * as m25 from './blackjack/definition';
import * as m26 from './block-drop/definition';
import * as m27 from './block-puzzle/definition';
import * as m28 from './boat-racing/definition';
import * as m29 from './boss-battle/definition';
import * as m30 from './bottle-flip/definition';
import * as m31 from './bowling/definition';
import * as m32 from './boxing/definition';
import * as m33 from './brain-training/definition';
import * as m34 from './brick-breaker/definition';
import * as m35 from './bubble-shooter/definition';
import * as m36 from './bulls-and-cows/definition';
import * as m37 from './business-simulator/definition';
import * as m38 from './candy-match/definition';
import * as m39 from './cannon-battle/definition';
import * as m40 from './cannon-shooter/definition';
import * as m41 from './capital-city-quiz/definition';
import * as m42 from './castle-defense/definition';
import * as m43 from './catch-falling-objects/definition';
import * as m44 from './categories-game/definition';
import * as m45 from './character-dress-up/definition';
import * as m46 from './checkers/definition';
import * as m47 from './chess/definition';
import * as m48 from './chess-puzzle/definition';
import * as m49 from './chess-tactics/definition';
import * as m50 from './chinese-checkers/definition';
import * as m51 from './circle-jump/definition';
import * as m52 from './circuit-racing/definition';
import * as m53 from './click-speed-test/definition';
import * as m54 from './clicker-empire/definition';
import * as m55 from './cloud-jumper/definition';
import * as m56 from './code-breaker/definition';
import * as m57 from './coin-toss/definition';
import * as m58 from './color-learning/definition';
import * as m59 from './color-match-cards/definition';
import * as m60 from './color-switch/definition';
import * as m61 from './color-tap/definition';
import * as m62 from './coloring-game/definition';
import * as m63 from './connect-dots-drawing/definition';
import * as m64 from './connect-four/definition';
import * as m65 from './connect-the-dots/definition';
import * as m66 from './cookie-factory/definition';
import * as m67 from './country-guess/definition';
import * as m68 from './crazy-eights/definition';
import * as m69 from './cricket-batting/definition';
import * as m70 from './cricket-bowling/definition';
import * as m71 from './cricket-super-over/definition';
import * as m72 from './crossword/definition';
import * as m73 from './cryptogram/definition';
import * as m74 from './darts/definition';
import * as m75 from './dino-runner/definition';
import * as m76 from './dominoes/definition';
import * as m77 from './draughts-variants/definition';
import * as m78 from './drawing-guess/definition';
import * as m79 from './drift-challenge/definition';
import * as m80 from './duck-target/definition';
import * as m81 from './dungeon-shooter/definition';
import * as m82 from './endless-jumper/definition';
import * as m83 from './endless-runner/definition';
import * as m84 from './endless-traffic-driving/definition';
import * as m85 from './escape-maze/definition';
import * as m86 from './falling-ball/definition';
import * as m87 from './falling-blocks/definition';
import * as m88 from './farm-simulator/definition';
import * as m89 from './finish-the-word/definition';
import * as m90 from './five-letter-word/definition';
import * as m91 from './flag-quiz/definition';
import * as m92 from './flow-connect/definition';
import * as m93 from './formula-racing/definition';
import * as m94 from './freecell/definition';
import * as m95 from './fruit-slice/definition';
import * as m96 from './geography-quiz/definition';
import * as m97 from './go/definition';
import * as m98 from './golf/definition';
import * as m99 from './golf-solitaire/definition';
import * as m100 from './gomoku/definition';
import * as m101 from './guess-the-number/definition';
import * as m102 from './guess-the-phrase/definition';
import * as m103 from './guess-the-word/definition';
import * as m104 from './hangman/definition';
import * as m105 from './hearts/definition';
import * as m106 from './hex/definition';
import * as m107 from './hidden-object/definition';
import * as m108 from './higher-or-lower/definition';
import * as m109 from './highway-racer/definition';
import * as m110 from './hill-racer/definition';
import * as m111 from './history-quiz/definition';
import * as m112 from './horse-race-sim/definition';
import * as m113 from './hotel-manager/definition';
import * as m114 from './idle-factory/definition';
import * as m115 from './idle-miner/definition';
import * as m116 from './iq-challenge/definition';
import * as m117 from './jet-ski-racing/definition';
import * as m118 from './jetpack-runner/definition';
import * as m119 from './jigsaw-puzzle/definition';
import * as m120 from './jumping-ball/definition';
import * as m121 from './kakuro/definition';
import * as m122 from './keep-the-ball-up/definition';
import * as m123 from './kids-counting/definition';
import * as m124 from './kingdom-builder/definition';
import * as m125 from './klondike-solitaire/definition';
import * as m126 from './knife-throw/definition';
import * as m127 from './language-vocabulary/definition';
import * as m128 from './letter-connect/definition';
import * as m129 from './letter-grid/definition';
import * as m130 from './lights-out/definition';
import * as m131 from './local-pictionary/definition';
import * as m132 from './logic-deduction/definition';
import * as m133 from './logic-grid/definition';
import * as m134 from './logo-style-quiz/definition';
import * as m135 from './ludo/definition';
import * as m136 from './lunar-lander/definition';
import * as m137 from './mancala/definition';
import * as m138 from './mandala-coloring/definition';
import * as m139 from './mastermind/definition';
import * as m140 from './match-three/definition';
import * as m141 from './matchstick-puzzle/definition';
import * as m142 from './math-puzzle/definition';
import * as m143 from './math-quiz/definition';
import * as m144 from './math-racing/definition';
import * as m145 from './maze/definition';
import * as m146 from './maze-muncher/definition';
import * as m147 from './memory-cards/definition';
import * as m148 from './memory-match/definition';
import * as m149 from './memory-sequence/definition';
import * as m150 from './memory-test/definition';
import * as m151 from './memory-training/definition';
import * as m152 from './mental-math/definition';
import * as m153 from './minesweeper/definition';
import * as m154 from './mini-city-builder/definition';
import * as m155 from './mini-civilization/definition';
import * as m156 from './mini-golf/definition';
import * as m157 from './mini-tycoon/definition';
import * as m158 from './missile-defense/definition';
import * as m159 from './missing-letters/definition';
import * as m160 from './motorcycle-racing/definition';
import * as m161 from './multiplication-challenge/definition';
import * as m162 from './nine-mens-morris/definition';
import * as m163 from './nonogram/definition';
import * as m164 from './number-merge-2048/definition';
import * as m165 from './number-sequence/definition';
import * as m166 from './paint-by-number/definition';
import * as m167 from './parking-challenge/definition';
import * as m168 from './parking-puzzle/definition';
import * as m169 from './pattern-puzzle/definition';
import * as m170 from './pattern-recognition/definition';
import * as m171 from './peg-solitaire/definition';
import * as m172 from './penalty-shootout/definition';
import * as m173 from './perfect-timing/definition';
import * as m174 from './periodic-table-quiz/definition';
import * as m175 from './pipe-connect/definition';
import * as m176 from './pixel-art/definition';
import * as m177 from './poker-vs-computer/definition';
import * as m178 from './police-chase/definition';
import * as m179 from './pong/definition';
import * as m180 from './pool/definition';
import * as m181 from './precision-target/definition';
import * as m182 from './programming-quiz/definition';
import * as m183 from './pyramid-solitaire/definition';
import * as m184 from './quick-draw/definition';
import * as m185 from './reaction-test-pro/definition';
import * as m186 from './reaction-timer/definition';
import * as m187 from './reflex-test/definition';
import * as m188 from './resource-manager/definition';
import * as m189 from './restaurant-simulator/definition';
import * as m190 from './reversi/definition';
import * as m191 from './rhythm-runner/definition';
import * as m192 from './road-hopper/definition';
import * as m193 from './robot-shooter/definition';
import * as m194 from './rock-paper-scissors/definition';
import * as m195 from './rummy-vs-computer/definition';
import * as m196 from './science-quiz/definition';
import * as m197 from './shape-drawing/definition';
import * as m198 from './shape-matching/definition';
import * as m199 from './shop-simulator/definition';
import * as m200 from './simon-memory/definition';
import * as m201 from './sky-hopper/definition';
import * as m202 from './sliding-puzzle/definition';
import * as m203 from './snake/definition';
import * as m204 from './snakes-and-ladders/definition';
import * as m205 from './soccer-free-kick/definition';
import * as m206 from './sokoban/definition';
import * as m207 from './space-combat/definition';
import * as m208 from './space-racing/definition';
import * as m209 from './space-shooter/definition';
import * as m210 from './spades/definition';
import * as m211 from './speed-typing/definition';
import * as m212 from './spelling-challenge/definition';
import * as m213 from './spider-solitaire/definition';
import * as m214 from './spin-the-wheel/definition';
import * as m215 from './spiral-drop/definition';
import * as m216 from './spot-the-difference/definition';
import * as m217 from './sprint-race/definition';
import * as m218 from './stack-blocks/definition';
import * as m219 from './stack-tower/definition';
import * as m220 from './stock-market-sim/definition';
import * as m221 from './sudoku/definition';
import * as m222 from './survival-arena/definition';
import * as m223 from './table-tennis/definition';
import * as m224 from './tangram/definition';
import * as m225 from './tank-battle/definition';
import * as m226 from './tank-shooter/definition';
import * as m227 from './target-shooting/definition';
import * as m228 from './tennis/definition';
import * as m229 from './three-card-game/definition';
import * as m230 from './tic-tac-toe/definition';
import * as m231 from './tile-solitaire/definition';
import * as m232 from './tile-word-builder/definition';
import * as m233 from './top-down-racing/definition';
import * as m234 from './tower-defense/definition';
import * as m235 from './tower-of-hanoi/definition';
import * as m236 from './trading-simulator/definition';
import * as m237 from './traffic-racer/definition';
import * as m238 from './tripeaks/definition';
import * as m239 from './truck-driving/definition';
import * as m240 from './typing-challenge/definition';
import * as m241 from './typing-tutor/definition';
import * as m242 from './unblock-puzzle/definition';
import * as m243 from './vocabulary-challenge/definition';
import * as m244 from './vocabulary-quiz/definition';
import * as m245 from './war-card/definition';
import * as m246 from './water-sort/definition';
import * as m247 from './whack-a-mole/definition';
import * as m248 from './word-builder/definition';
import * as m249 from './word-ladder/definition';
import * as m250 from './word-scramble/definition';
import * as m251 from './word-search/definition';
import * as m252 from './zombie-survival/definition';

export const DEFINITION_MODULES: Record<string, Record<string, unknown>> = {
  'aim-trainer': m0,
  'air-hockey': m1,
  'airport-manager': m2,
  'alien-defender': m3,
  'alien-invasion': m4,
  'alien-shooter': m5,
  'alphabet-game': m6,
  'anagram': m7,
  'archery': m8,
  'archery-challenge': m9,
  'army-strategy': m10,
  'asteroid-blaster': m11,
  'asteroid-defense': m12,
  'avoid-obstacles': m13,
  'baccarat': m14,
  'backgammon': m15,
  'balance-game': m16,
  'balance-puzzle': m17,
  'ball-bounce': m18,
  'ball-sort': m19,
  'baseball-batting': m20,
  'basketball-shot': m21,
  'battleship': m22,
  'bike-race': m23,
  'binary-puzzle': m24,
  'blackjack': m25,
  'block-drop': m26,
  'block-puzzle': m27,
  'boat-racing': m28,
  'boss-battle': m29,
  'bottle-flip': m30,
  'bowling': m31,
  'boxing': m32,
  'brain-training': m33,
  'brick-breaker': m34,
  'bubble-shooter': m35,
  'bulls-and-cows': m36,
  'business-simulator': m37,
  'candy-match': m38,
  'cannon-battle': m39,
  'cannon-shooter': m40,
  'capital-city-quiz': m41,
  'castle-defense': m42,
  'catch-falling-objects': m43,
  'categories-game': m44,
  'character-dress-up': m45,
  'checkers': m46,
  'chess': m47,
  'chess-puzzle': m48,
  'chess-tactics': m49,
  'chinese-checkers': m50,
  'circle-jump': m51,
  'circuit-racing': m52,
  'click-speed-test': m53,
  'clicker-empire': m54,
  'cloud-jumper': m55,
  'code-breaker': m56,
  'coin-toss': m57,
  'color-learning': m58,
  'color-match-cards': m59,
  'color-switch': m60,
  'color-tap': m61,
  'coloring-game': m62,
  'connect-dots-drawing': m63,
  'connect-four': m64,
  'connect-the-dots': m65,
  'cookie-factory': m66,
  'country-guess': m67,
  'crazy-eights': m68,
  'cricket-batting': m69,
  'cricket-bowling': m70,
  'cricket-super-over': m71,
  'crossword': m72,
  'cryptogram': m73,
  'darts': m74,
  'dino-runner': m75,
  'dominoes': m76,
  'draughts-variants': m77,
  'drawing-guess': m78,
  'drift-challenge': m79,
  'duck-target': m80,
  'dungeon-shooter': m81,
  'endless-jumper': m82,
  'endless-runner': m83,
  'endless-traffic-driving': m84,
  'escape-maze': m85,
  'falling-ball': m86,
  'falling-blocks': m87,
  'farm-simulator': m88,
  'finish-the-word': m89,
  'five-letter-word': m90,
  'flag-quiz': m91,
  'flow-connect': m92,
  'formula-racing': m93,
  'freecell': m94,
  'fruit-slice': m95,
  'geography-quiz': m96,
  'go': m97,
  'golf': m98,
  'golf-solitaire': m99,
  'gomoku': m100,
  'guess-the-number': m101,
  'guess-the-phrase': m102,
  'guess-the-word': m103,
  'hangman': m104,
  'hearts': m105,
  'hex': m106,
  'hidden-object': m107,
  'higher-or-lower': m108,
  'highway-racer': m109,
  'hill-racer': m110,
  'history-quiz': m111,
  'horse-race-sim': m112,
  'hotel-manager': m113,
  'idle-factory': m114,
  'idle-miner': m115,
  'iq-challenge': m116,
  'jet-ski-racing': m117,
  'jetpack-runner': m118,
  'jigsaw-puzzle': m119,
  'jumping-ball': m120,
  'kakuro': m121,
  'keep-the-ball-up': m122,
  'kids-counting': m123,
  'kingdom-builder': m124,
  'klondike-solitaire': m125,
  'knife-throw': m126,
  'language-vocabulary': m127,
  'letter-connect': m128,
  'letter-grid': m129,
  'lights-out': m130,
  'local-pictionary': m131,
  'logic-deduction': m132,
  'logic-grid': m133,
  'logo-style-quiz': m134,
  'ludo': m135,
  'lunar-lander': m136,
  'mancala': m137,
  'mandala-coloring': m138,
  'mastermind': m139,
  'match-three': m140,
  'matchstick-puzzle': m141,
  'math-puzzle': m142,
  'math-quiz': m143,
  'math-racing': m144,
  'maze': m145,
  'maze-muncher': m146,
  'memory-cards': m147,
  'memory-match': m148,
  'memory-sequence': m149,
  'memory-test': m150,
  'memory-training': m151,
  'mental-math': m152,
  'minesweeper': m153,
  'mini-city-builder': m154,
  'mini-civilization': m155,
  'mini-golf': m156,
  'mini-tycoon': m157,
  'missile-defense': m158,
  'missing-letters': m159,
  'motorcycle-racing': m160,
  'multiplication-challenge': m161,
  'nine-mens-morris': m162,
  'nonogram': m163,
  'number-merge-2048': m164,
  'number-sequence': m165,
  'paint-by-number': m166,
  'parking-challenge': m167,
  'parking-puzzle': m168,
  'pattern-puzzle': m169,
  'pattern-recognition': m170,
  'peg-solitaire': m171,
  'penalty-shootout': m172,
  'perfect-timing': m173,
  'periodic-table-quiz': m174,
  'pipe-connect': m175,
  'pixel-art': m176,
  'poker-vs-computer': m177,
  'police-chase': m178,
  'pong': m179,
  'pool': m180,
  'precision-target': m181,
  'programming-quiz': m182,
  'pyramid-solitaire': m183,
  'quick-draw': m184,
  'reaction-test-pro': m185,
  'reaction-timer': m186,
  'reflex-test': m187,
  'resource-manager': m188,
  'restaurant-simulator': m189,
  'reversi': m190,
  'rhythm-runner': m191,
  'road-hopper': m192,
  'robot-shooter': m193,
  'rock-paper-scissors': m194,
  'rummy-vs-computer': m195,
  'science-quiz': m196,
  'shape-drawing': m197,
  'shape-matching': m198,
  'shop-simulator': m199,
  'simon-memory': m200,
  'sky-hopper': m201,
  'sliding-puzzle': m202,
  'snake': m203,
  'snakes-and-ladders': m204,
  'soccer-free-kick': m205,
  'sokoban': m206,
  'space-combat': m207,
  'space-racing': m208,
  'space-shooter': m209,
  'spades': m210,
  'speed-typing': m211,
  'spelling-challenge': m212,
  'spider-solitaire': m213,
  'spin-the-wheel': m214,
  'spiral-drop': m215,
  'spot-the-difference': m216,
  'sprint-race': m217,
  'stack-blocks': m218,
  'stack-tower': m219,
  'stock-market-sim': m220,
  'sudoku': m221,
  'survival-arena': m222,
  'table-tennis': m223,
  'tangram': m224,
  'tank-battle': m225,
  'tank-shooter': m226,
  'target-shooting': m227,
  'tennis': m228,
  'three-card-game': m229,
  'tic-tac-toe': m230,
  'tile-solitaire': m231,
  'tile-word-builder': m232,
  'top-down-racing': m233,
  'tower-defense': m234,
  'tower-of-hanoi': m235,
  'trading-simulator': m236,
  'traffic-racer': m237,
  'tripeaks': m238,
  'truck-driving': m239,
  'typing-challenge': m240,
  'typing-tutor': m241,
  'unblock-puzzle': m242,
  'vocabulary-challenge': m243,
  'vocabulary-quiz': m244,
  'war-card': m245,
  'water-sort': m246,
  'whack-a-mole': m247,
  'word-builder': m248,
  'word-ladder': m249,
  'word-scramble': m250,
  'word-search': m251,
  'zombie-survival': m252,
};
