import type { AchievementDefinition } from '@/types';

export const achievements: AchievementDefinition[] = [
  {
    id: 'sudoku.first-solve',
    gameId: 'sudoku',
    name: 'Solved It',
    description: 'Complete your first Sudoku.',
    target: 1,
    icon: '🔢',
    coins: 20,
  },
  {
    id: 'sudoku.hard-solve',
    gameId: 'sudoku',
    name: 'Hard Mode',
    description: 'Complete a Hard puzzle.',
    target: 1,
    icon: '🧠',
    coins: 60,
  },
  {
    id: 'sudoku.no-hints',
    gameId: 'sudoku',
    name: 'Unassisted',
    description: 'Complete a puzzle without using a hint.',
    target: 1,
    icon: '🎯',
    coins: 40,
  },
  {
    id: 'sudoku.no-mistakes',
    gameId: 'sudoku',
    name: 'Flawless',
    description: 'Complete a puzzle with no incorrect entries.',
    target: 1,
    icon: '✨',
    coins: 45,
  },
  {
    id: 'sudoku.fast',
    gameId: 'sudoku',
    name: 'Speed Solver',
    description: 'Complete an Easy puzzle in under five minutes.',
    target: 1,
    icon: '⏱️',
    coins: 30,
  },
  {
    id: 'sudoku.solve-10',
    gameId: 'sudoku',
    name: 'Dedicated',
    description: 'Complete 10 puzzles.',
    target: 10,
    icon: '📚',
    coins: 50,
  },
];
