import { site } from '@/config/site';
import { categoryLabel, hasComputerOpponent, isTwoPlayer } from '@/seo/content';
import type { GameDefinition } from '@/types';

/**
 * Shared by the runtime <PageMeta> and the build-time prerenderer so the
 * titles, descriptions and canonical URLs crawlers see always match.
 */

const MAX_TITLE = 60;
const MAX_DESCRIPTION = 160;

/** Paths are canonicalised with a trailing slash, matching the static files. */
export function canonicalPath(pathname: string): string {
  const clean = pathname.split(/[?#]/)[0] || '/';
  return clean.endsWith('/') ? clean : `${clean}/`;
}

export function absoluteUrl(pathname: string): string {
  return `${site.siteUrl}${canonicalPath(pathname)}`;
}

export function withBrand(title: string): string {
  return `${title} | ${site.siteName}`;
}

/** Leads with the phrase people type: "play free online games". */
export function homeTitle(): string {
  return withBrand('Play Free Online Games – No Download');
}

/** Words that already tell the searcher what kind of thing the title is. */
const KIND_WORDS =
  /\b(game|games|puzzle|quiz|solitaire|challenge|test|trainer|tutor|training|simulator|shootout|race|racing|runner|defense|blaster|builder|search|sort|merge)\b/i;

/**
 * Picks the most descriptive title that still fits in a search result. The
 * variants mirror real queries: "snake game", "chess vs computer",
 * "connect four 2 player".
 */
export function gameTitle(game: GameDefinition): string {
  // "Poker vs Computer" already says who you play against.
  const namesOpponent = /\bvs\b/i.test(game.title);
  const name = KIND_WORDS.test(game.title) || namesOpponent ? game.title : `${game.title} Game`;
  const vsAi = hasComputerOpponent(game) && !namesOpponent;
  const twoPlayer = isTwoPlayer(game);
  const candidates = [
    vsAi && twoPlayer ? `${game.title} – Play Free vs Computer or 2 Player` : '',
    vsAi && twoPlayer ? `${game.title} – Free vs Computer or 2 Player` : '',
    vsAi ? `${game.title} vs Computer – Play Free Online` : '',
    twoPlayer ? `${game.title} – Free Online 2 Player Game` : '',
    `${name} – Play Free Online, No Download`,
    `${name} – Play Free Online`,
    `${game.title} – Play Free Online`,
  ].filter(Boolean);
  for (const c of candidates) {
    if (withBrand(c).length <= MAX_TITLE) return withBrand(c);
  }
  return candidates[candidates.length - 1];
}

export function clampDescription(text: string): string {
  if (text.length <= MAX_DESCRIPTION) return text;
  const cut = text.slice(0, MAX_DESCRIPTION - 1);
  return `${cut.slice(0, cut.lastIndexOf(' '))}…`;
}

export function gameDescription(game: GameDefinition): string {
  const lead = game.shortDescription.replace(/\.?$/, '.');
  return clampDescription(
    `${lead} Play ${game.title} free in your browser – no download, no sign-up, works on mobile.`,
  );
}

export function categoryTitle(name: string): string {
  return withBrand(`${categoryLabel({ name })} – Play Free Online`);
}

export function categoryDescription(name: string, blurb: string, count: number): string {
  const games = count === 1 ? '1 free game' : `${count} free games`;
  return clampDescription(
    `Play ${games} in the ${categoryLabel({ name }).toLowerCase()} category instantly in your browser. ${blurb} No download, no sign-up.`,
  );
}

export function collectionTitle(title: string): string {
  return withBrand(title).length <= MAX_TITLE ? withBrand(title) : title;
}

export function gamePath(id: string): string {
  return `/games/${id}/`;
}

export function categoryPath(slug: string): string {
  return `/categories/${slug}/`;
}

export type OgImageKind = 'games' | 'categories' | 'collections';

/** Share image generated by scripts/og-images.ts, relative to the site root. */
export function ogImagePath(kind: OgImageKind, slug: string): string {
  return `/og/${kind}/${slug}.jpg`;
}
