/**
 * Proverbs and public-domain quotations (authors who died long ago, or
 * traditional sayings). Used by Cryptogram and the typing games.
 */
export const SAYINGS: [text: string, source: string][] = [
  ['Actions speak louder than words.', 'Proverb'],
  ['A journey of a thousand miles begins with a single step.', 'Chinese proverb'],
  ['Well begun is half done.', 'Aristotle'],
  ['Knowledge is power.', 'Francis Bacon'],
  ['Honesty is the best policy.', 'Proverb'],
  ['Where there is a will, there is a way.', 'Proverb'],
  ['Early to bed and early to rise makes a man healthy, wealthy and wise.', 'Benjamin Franklin'],
  ['Well done is better than well said.', 'Benjamin Franklin'],
  ['An investment in knowledge pays the best interest.', 'Benjamin Franklin'],
  ['Lost time is never found again.', 'Benjamin Franklin'],
  ['All the world is a stage.', 'William Shakespeare'],
  ['Brevity is the soul of wit.', 'William Shakespeare'],
  ['The course of true love never did run smooth.', 'William Shakespeare'],
  ['To be or not to be, that is the question.', 'William Shakespeare'],
  ['Whatever you are, be a good one.', 'Abraham Lincoln'],
  ['The secret of getting ahead is getting started.', 'Saying'],
  ['Kindness is a language everyone understands.', 'Saying'],
  ['Experience is simply the name we give our mistakes.', 'Oscar Wilde'],
  ['It does not matter how slowly you go as long as you do not stop.', 'Attributed to Confucius'],
  ['The only true wisdom is in knowing you know nothing.', 'Attributed to Socrates'],
  ['Happiness depends upon ourselves.', 'Attributed to Aristotle'],
  ['Fortune favours the bold.', 'Latin proverb'],
  ['Patience is bitter, but its fruit is sweet.', 'Proverb'],
  ['A picture is worth a thousand words.', 'Proverb'],
  ['The early bird catches the worm.', 'Proverb'],
  ['Every cloud has a silver lining.', 'Proverb'],
  ['Practice makes perfect.', 'Proverb'],
  ['Two heads are better than one.', 'Proverb'],
  ['Rome was not built in a day.', 'Proverb'],
  ['Slow and steady wins the race.', 'Aesop'],
  ['Look before you leap.', 'Aesop'],
  ['United we stand, divided we fall.', 'Aesop'],
  ['Necessity is the mother of invention.', 'Proverb'],
  ['The pen is mightier than the sword.', 'Edward Bulwer-Lytton'],
  ['Nothing is impossible to a willing heart.', 'Proverb'],
  ['Great minds think alike.', 'Proverb'],
  ['Laughter is the best medicine.', 'Proverb'],
  ['Time and tide wait for no man.', 'Proverb'],
  ['A friend in need is a friend indeed.', 'Proverb'],
  ['Better late than never.', 'Proverb'],
  ['Do not count your chickens before they hatch.', 'Aesop'],
  ['Still waters run deep.', 'Proverb'],
  ['The best things in life are free.', 'Proverb'],
  ['Where there is smoke, there is fire.', 'Proverb'],
  ['You cannot judge a book by its cover.', 'Proverb'],
  ['All that glitters is not gold.', 'William Shakespeare'],
  ['A watched pot never boils.', 'Proverb'],
  ['Imagination is the eye of the soul.', 'Joseph Joubert'],
  ['A smooth sea never made a skilled sailor.', 'Proverb'],
];
