/**
 * Builds original chess puzzles by mining positions from the engine playing
 * itself with random noise, then classifying each position exactly:
 *   - mate in 1 / 2 / 3 with a unique first move (verified by mate.ts), and
 *   - tactics where one move wins clearly more than every alternative.
 * Run: npx vite-node scripts/gen-chess-puzzles.ts
 */
import { writeFileSync } from 'node:fs';
import { Chess, toUci } from '../src/games/_shared/chess/engine';
import { MATE, analyse, bestMove, evaluate } from '../src/games/_shared/chess/ai';
import { mateMoves } from '../src/games/_shared/chess/mate';

const WANT = { m1: 60, m2: 90, m3: 0, tactic: 100 };
const mate1: { fen: string; move: string }[] = [];
const mate2: { fen: string; move: string }[] = [];
const mate3: { fen: string; move: string }[] = [];
const tactics: { fen: string; accept: string[]; gain: number }[] = [];
const seen = new Set<string>();
const full = () => mate1.length >= WANT.m1 && mate2.length >= WANT.m2 && mate3.length >= WANT.m3 && tactics.length >= WANT.tactic;

function classify(c: Chess): void {
  const key = c.key();
  if (seen.has(key)) return;
  seen.add(key);
  const scores = analyse(c, 3).sort((a, b) => b.score - a.score);
  if (scores.length < 2) return;
  const [best, second] = scores;
  if (best.score > MATE - 20) {
    for (const n of [1, 2, 3]) {
      const list = n === 1 ? mate1 : n === 2 ? mate2 : mate3;
      if (list.length >= (n === 1 ? WANT.m1 : n === 2 ? WANT.m2 : WANT.m3)) continue;
      const solutions = mateMoves(c, n);
      if (!solutions.length) continue;
      // Unique key move, and no shorter mate available.
      if (solutions.length === 1) list.push({ fen: c.fen(), move: toUci(solutions[0]) });
      return;
    }
    return;
  }
  if (tactics.length >= WANT.tactic) return;
  const before = evaluate(c);
  if (best.score >= 220 && best.score - second.score >= 250 && before <= 120 && before >= -250) {
    const accept = scores.filter((s) => s.score >= best.score - 60).map((s) => toUci(s.move));
    if (accept.length <= 2) tactics.push({ fen: c.fen(), accept, gain: Math.round(best.score - before) });
  }
}

let games = 0;
const t0 = Date.now();
while (!full() && games < 1500) {
  games++;
  const c = new Chess();
  const noise = 60 + Math.random() * 160;
  for (let ply = 0; ply < 140; ply++) {
    if (c.status() !== 'play') break;
    if (ply >= 14 && ply % 2 === games % 2) classify(c);
    const m = bestMove(c, { maxDepth: 2, timeMs: 200, noise });
    if (m === null) break;
    c.play(m);
  }
  if (games % 10 === 0) save();
  if (games % 10 === 0)
    console.log(`games ${games} m1 ${mate1.length} m2 ${mate2.length} m3 ${mate3.length} tactics ${tactics.length} (${Math.round((Date.now() - t0) / 1000)}s)`);
}

function save() {
  const body = `// Generated by scripts/gen-chess-puzzles.ts from engine self-play. Original positions.
export interface MatePuzzle {
  fen: string;
  /** The unique key move in UCI notation. */
  move: string;
}
export interface TacticPuzzle {
  fen: string;
  /** Moves accepted as correct (UCI). */
  accept: string[];
  /** Approximate advantage gained, in centipawns. */
  gain: number;
}

export const MATE_IN_1: MatePuzzle[] = ${JSON.stringify(mate1, null, 1)};

export const MATE_IN_2: MatePuzzle[] = ${JSON.stringify(mate2, null, 1)};

export const MATE_IN_3: MatePuzzle[] = ${JSON.stringify(mate3, null, 1)};

export const TACTICS: TacticPuzzle[] = ${JSON.stringify(tactics, null, 1)};
`;
writeFileSync('src/games/_shared/chess/puzzles.ts', body);
}
save();
console.log('done', { games, m1: mate1.length, m2: mate2.length, m3: mate3.length, tactics: tactics.length });
