/**
 * Regenerates the game checklist in PROJECT_STATUS.md from the source tree:
 * a game is ticked only when src/games/<id>/definition.ts exists (which is
 * also exactly what registers it in the app). Run: node scripts/update-status.mjs
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const planned = readFileSync(resolve(root, 'src/data/plannedGames.ts'), 'utf8');
const NAMES = {
  ARCADE: 'Arcade',
  PUZZLE: 'Puzzle',
  WORD: 'Word',
  BOARD: 'Board',
  CARD: 'Card',
  SPORTS: 'Sports',
  RACING: 'Racing',
  ACTION: 'Action',
  STRATEGY: 'Strategy / Simulation',
  EDUCATIONAL: 'Educational',
  CASUAL: 'Casual',
  CREATIVE: 'Creative',
  BRAIN: 'Brain / Logic',
};

const parts = planned.split(/const (\w+): Row\[\] = \[/);
let total = 0;
let done = 0;
const sections = [];
for (let i = 1; i < parts.length; i += 2) {
  const rows = [...parts[i + 1].split('];')[0].matchAll(/\['([^']+)', '([^']+)'/g)];
  const lines = rows.map(([, id, title]) => {
    const ok = existsSync(resolve(root, 'src/games', id, 'definition.ts'));
    total++;
    if (ok) done++;
    return `- [${ok ? 'x' : ' '}] ${title}`;
  });
  const n = lines.filter((l) => l.startsWith('- [x]')).length;
  sections.push(`### ${NAMES[parts[i]] ?? parts[i]} (${n}/${lines.length})\n\n${lines.join('\n')}`);
}

const block = `<!-- games:start -->\n**${done} of ${total} games playable.** Generated by \`node scripts/update-status.mjs\`; a game is ticked only when its folder registers a playable definition.\n\n${sections.join('\n\n')}\n<!-- games:end -->`;

const file = resolve(root, 'PROJECT_STATUS.md');
let status = readFileSync(file, 'utf8');
if (status.includes('<!-- games:start -->')) {
  status = status.replace(/<!-- games:start -->[\s\S]*<!-- games:end -->/, block);
} else {
  status = status.replace(/## Games\n[\s\S]*?\n---\n/, `## Games\n\n${block}\n\n---\n`);
}
status = status.replace(/\| Games playable \| \d+ of \d+ catalogued \|/, `| Games playable | ${done} of ${total} catalogued |`);
writeFileSync(file, status);
console.log(`status: ${done}/${total} playable`);
