// Generated by scripts/gen-chess-puzzles.ts from engine self-play. Original positions.
export interface MatePuzzle {
  fen: string;
  /** The unique key move in UCI notation. */
  move: string;
}
export interface TacticPuzzle {
  fen: string;
  /** Moves accepted as correct (UCI). */
  accept: string[];
  /** Approximate advantage gained, in centipawns. */
  gain: number;
}

export const MATE_IN_1: MatePuzzle[] = [
 {
  "fen": "5R2/k5r1/p6K/8/5Pqp/8/8/8 b - - 3 47",
  "move": "g4g6"
 },
 {
  "fen": "7Q/8/8/2N5/2k5/4K3/3R4/1R6 w - - 3 62",
  "move": "h8d4"
 },
 {
  "fen": "4r3/1k6/2qB3p/6p1/p1p5/P6b/1P5K/2R5 b - - 3 54",
  "move": "c6g2"
 },
 {
  "fen": "rn1q1bnr/3b1Q2/p1pkp2p/1p1pNp2/3P1B2/P1P1P1P1/1P1N1P1P/R3KB1R w KQ - 3 13",
  "move": "e5c4"
 },
 {
  "fen": "r1k1r3/3n2p1/p3pp2/P1P1P2p/3PbPnP/1q3N2/3BK1P1/R3Q2R b - - 2 27",
  "move": "e4d3"
 },
 {
  "fen": "4k2r/8/6p1/1pb1Pp1p/7P/1q6/8/K7 b k - 11 65",
  "move": "c5d4"
 },
 {
  "fen": "Q4q1k/3R4/8/5p1p/5PpP/6P1/4K3/8 w - - 11 58",
  "move": "a8f8"
 },
 {
  "fen": "3rk3/2p2pp1/1pn1p3/p5P1/P5P1/P2P4/1NK2P2/4q2r b - - 3 27",
  "move": "c6d4"
 },
 {
  "fen": "7k/8/1p6/pP3p1p/8/r1n5/7r/2K1R3 b - - 5 60",
  "move": "a3a1"
 },
 {
  "fen": "6r1/p3k3/B7/P1K5/4q2p/8/3b4/8 b - - 5 65",
  "move": "g8g5"
 },
 {
  "fen": "8/7k/2q5/7p/5K2/4r3/1pb5/8 b - - 13 62",
  "move": "c6h6"
 },
 {
  "fen": "r1b5/1p2k1pr/1nq1N2p/p1p1P2Q/1b2P1PP/8/PP1P2B1/R1B2RK1 w - - 4 22",
  "move": "h5f7"
 },
 {
  "fen": "6k1/8/1p1r1n2/1RpP3p/5p1P/2q2np1/4B1P1/r2N1KQR b - - 7 60",
  "move": "c3e1"
 },
 {
  "fen": "5r1r/6k1/4Q3/5P1p/7p/2P4P/6P1/5K2 w - - 3 46",
  "move": "e6g6"
 },
 {
  "fen": "4N3/R5Bk/6p1/7p/5P2/6P1/2K5/6R1 w - - 1 45",
  "move": "e8f6"
 },
 {
  "fen": "3rk3/1p3p2/p5p1/2p5/8/P1B3b1/1PP4q/RN3K2 b - - 6 34",
  "move": "h2f2"
 },
 {
  "fen": "6k1/4PR2/8/8/8/8/K7/8 w - - 1 57",
  "move": "e7e8q"
 },
 {
  "fen": "2Q5/2p3pk/3b4/7b/1q2pP2/2p5/8/2K5 b - - 3 56",
  "move": "b4b2"
 },
 {
  "fen": "1k6/8/Q3P3/p5p1/1pPBRpP1/1P6/P4N2/6K1 w - - 1 52",
  "move": "d4e5"
 },
 {
  "fen": "k6r/1qQ5/8/p6P/P2P2P1/2R2B2/2n1R2N/7K w - - 1 56",
  "move": "c7b7"
 },
 {
  "fen": "3r1r1k/p5p1/1p4p1/4p2q/PP1n4/8/B1PPQb2/R1BK4 b - - 3 31",
  "move": "h5e2"
 },
 {
  "fen": "3k4/4R3/4Q3/p7/3p1P2/3q4/8/b3K3 w - - 4 56",
  "move": "e6d7"
 },
 {
  "fen": "2r5/8/N2k4/2N4p/1P2Q2P/3P3P/5P2/3K4 w - - 2 49",
  "move": "e4e6"
 },
 {
  "fen": "1r6/2kq4/6Q1/p1p1p2p/4B2P/2P1nP2/P7/R1K5 b - - 3 35",
  "move": "d7d1"
 },
 {
  "fen": "8/1p6/5k2/7p/3p1p1P/6p1/6P1/rR4KR b - - 2 44",
  "move": "a1b1"
 },
 {
  "fen": "8/1n6/8/2q4p/6p1/3K4/8/k5q1 b - - 3 69",
  "move": "g1e3"
 },
 {
  "fen": "1k3b1r/3Bp1p1/4P1bp/Q4p2/P4P2/4P1P1/R1P5/6K1 w - - 3 35",
  "move": "a2b2"
 },
 {
  "fen": "4r3/3k4/5Bb1/3p4/1P3P2/5nPP/1R6/2RK4 b - - 8 48",
  "move": "e8e1"
 },
 {
  "fen": "8/Q3B3/b6R/k2p4/7K/5r1P/2P3qP/8 w - - 6 47",
  "move": "a7a6"
 },
 {
  "fen": "3r2k1/5p2/7p/2p3p1/2K3P1/1P3P1P/3q4/Q5R1 b - - 15 67",
  "move": "d2b4"
 },
 {
  "fen": "3k4/4R3/3B4/5R1p/2N4P/2P5/8/6K1 w - - 7 53",
  "move": "f5f8"
 },
 {
  "fen": "8/8/R7/p1P5/P2P1P1k/7P/6K1/8 w - - 1 67",
  "move": "a6h6"
 },
 {
  "fen": "8/8/6p1/1p5p/6qP/8/2k2K2/q7 b - - 1 65",
  "move": "a1g1"
 },
 {
  "fen": "2k4r/pp3bp1/2n4p/4p3/P4P1P/RnP5/KP4P1/2r3NR b - - 1 28",
  "move": "c1a1"
 },
 {
  "fen": "2b2r2/p7/3k1p2/p5P1/P7/3n4/r4PPR/3B1KN1 b - - 4 33",
  "move": "a2f2"
 },
 {
  "fen": "rn6/1R6/p4Q2/2p4k/P3P3/3P1Pp1/7b/5K1R w - - 2 34",
  "move": "b7h7"
 },
 {
  "fen": "3Qn1kr/3pR3/6p1/7p/4B3/1r3P2/1PR4K/1NB2q2 w - - 4 34",
  "move": "d8e8"
 },
 {
  "fen": "6k1/8/6p1/1p3p1p/5P1P/3rR1K1/r7/6R1 b - - 2 42",
  "move": "d3e3"
 },
 {
  "fen": "8/1k6/6pp/8/7K/4q3/p2r4/8 b - - 3 64",
  "move": "d2d4"
 },
 {
  "fen": "7k/3R4/4Qp2/4p3/P3P3/8/5PKP/7B w - - 7 46",
  "move": "e6e8"
 },
 {
  "fen": "8/8/5pp1/8/4P3/2Q5/k6P/4R2K w - - 8 53",
  "move": "e1a1"
 },
 {
  "fen": "8/2p2pp1/3bk3/3p3P/3P4/2r5/r7/5K1n b - - 3 49",
  "move": "c3c1"
 },
 {
  "fen": "7r/3k1pp1/b3p1p1/4P3/1b2nP2/7P/r2B2P1/4K1NR b - - 9 29",
  "move": "a2a1"
 },
 {
  "fen": "r3r1k1/4b2R/qp1p4/p1pPpQ2/P1P1P3/1PN5/5P2/RK6 w - - 1 55",
  "move": "f5f7"
 },
 {
  "fen": "4kr2/1p4p1/2b1p3/1P6/3p3P/8/4N1pR/6K1 b - - 0 36",
  "move": "f8f1"
 },
 {
  "fen": "2kr4/1b6/5p2/p3p2B/7P/2N3KR/5r2/6N1 b - - 2 52",
  "move": "f2g2"
 },
 {
  "fen": "2b1B2k/2p5/4pp2/5N2/3P4/2n3RP/7q/rRK5 b - - 6 49",
  "move": "a1b1"
 },
 {
  "fen": "R6R/1kp5/1p4p1/3P1p2/pqP5/5N2/r2N2PK/8 w - - 2 48",
  "move": "h8b8"
 }
];

export const MATE_IN_2: MatePuzzle[] = [
 {
  "fen": "5R2/k5r1/p7/7K/5P1p/7q/8/8 b - - 1 46",
  "move": "h3g4"
 },
 {
  "fen": "2q1r3/1k6/3B3p/6p1/p1p5/P6b/1P6/2R4K b - - 1 53",
  "move": "c8c6"
 },
 {
  "fen": "rn1q1bnr/3bk3/p1p1p1Qp/1p1pNp2/3P1B2/P1P1P1P1/1P1N1P1P/R3KB1R w KQ - 1 12",
  "move": "g6f7"
 },
 {
  "fen": "r1k1r3/1q1n2p1/p3pp2/P1P1P2p/3PbPnP/5N2/3B2P1/R2KQ2R b - - 0 26",
  "move": "b7b3"
 },
 {
  "fen": "1rk5/8/1p3Q2/p1pK4/P7/RPP1P3/8/8 w - - 14 62",
  "move": "d5c6"
 },
 {
  "fen": "4k2r/8/6p1/1pb1Pp1p/2q4P/8/8/1K6 b k - 9 64",
  "move": "c4b3"
 },
 {
  "fen": "7k/3R4/5q2/5p1p/5PpP/6P1/Q3K3/8 w - - 9 57",
  "move": "a2a8"
 },
 {
  "fen": "2r3k1/1p1p1p2/7p/p1p1q1p1/PbP1P3/1P3PPP/1r6/1RQ2RK1 b - - 4 23",
  "move": "e5g3"
 },
 {
  "fen": "7k/8/1p6/pP3p1p/4n3/r7/7r/1K2R3 b - - 3 59",
  "move": "e4c3"
 },
 {
  "fen": "6r1/p3k3/B1K5/P7/1q5p/8/3b4/8 b - - 3 64",
  "move": "b4e4"
 },
 {
  "fen": "r1b2k2/1p4pr/1nq4p/p1p1P2Q/1b2PNPP/8/PP1P2B1/R1B2RK1 w - - 2 21",
  "move": "f4e6"
 },
 {
  "fen": "6k1/8/1p1r1n2/1RpP3p/5p1P/2q3p1/3nB1P1/r2NK1QR b - - 5 59",
  "move": "d2f3"
 },
 {
  "fen": "5r1r/5k2/8/4QP1p/7p/2P4P/6P1/5K2 w - - 1 45",
  "move": "e5e6"
 },
 {
  "fen": "8/5Rk1/2p5/1p5p/3bp3/7P/3K4/rq6 b - - 1 42",
  "move": "g7f7"
 },
 {
  "fen": "4N2k/R5r1/6p1/7p/3B1P2/6P1/2K5/6R1 w - - 3 44",
  "move": "d4g7"
 },
 {
  "fen": "3rk3/1p3p2/p5p1/2p5/5b2/P1B5/1PP4q/RN2K3 b - - 4 33",
  "move": "f4g3"
 },
 {
  "fen": "7k/5R2/4P3/8/8/8/K7/8 w - - 3 56",
  "move": "e6e7"
 },
 {
  "fen": "k7/8/n3P3/pQ4p1/1pPBRpP1/1P6/P4N2/6K1 w - - 5 51",
  "move": "b5a6"
 },
 {
  "fen": "3k4/1q2b1r1/1P1pKp2/4p1p1/2P3P1/7P/8/8 b - c3 0 57",
  "move": "d6d5"
 },
 {
  "fen": "3k4/1q2b1r1/3p1p2/4pKp1/2P3P1/7P/8/8 b - - 1 59",
  "move": "d8d7"
 },
 {
  "fen": "3k4/4b1r1/5p2/2p5/4p2p/4q3/8/3K4 b - - 3 68",
  "move": "e3f2"
 },
 {
  "fen": "3k4/4b3/5p2/2p3r1/4p2p/4q3/2K5/8 b - - 5 69",
  "move": "g5g2"
 },
 {
  "fen": "k6r/2Q5/8/p6P/Pq1P2P1/2R2r2/2n1R1BN/7K w - - 7 55",
  "move": "g2f3"
 },
 {
  "fen": "6k1/8/r1p5/P2p3p/4p1pb/4P3/2q5/7K b - - 1 44",
  "move": "a6a5"
 },
 {
  "fen": "2k5/4p3/8/1p1rP3/p2p4/P2K1N2/6q1/7r b - - 5 52",
  "move": "g2f3"
 },
 {
  "fen": "4R3/2k5/4Q3/p7/3p1P2/3q4/8/b3K3 w - - 2 55",
  "move": "e8e7"
 },
 {
  "fen": "r6r/p3n1pp/4Q3/2q1p3/4Pk1P/3P4/P1p2PP1/4KB1R w K - 1 22",
  "move": "e6f7"
 },
 {
  "fen": "2r5/8/N5Q1/2Nk3p/1P5P/3P3P/5P2/3K4 w - - 0 48",
  "move": "g6e4"
 },
 {
  "fen": "1r6/2kq4/6Q1/p1pnp2p/4B2P/2P2P2/P1K5/R7 b - - 1 34",
  "move": "d5e3"
 },
 {
  "fen": "5br1/4pR2/1p4k1/1P1pP3/3P3B/4N2Q/P5P1/R2K4 w - - 0 38",
  "move": "h3f5"
 },
 {
  "fen": "2k5/4R3/P2p1Bp1/5p2/5P1p/5K1P/8/8 w - - 1 43",
  "move": "a6a7"
 },
 {
  "fen": "8/1p6/5k2/rR5p/3p1p1P/6p1/6P1/6KR b - - 0 43",
  "move": "a5a1"
 },
 {
  "fen": "r5k1/1p4p1/8/1NQ4p/p1P3b1/1P4bq/P7/6K1 b - - 5 34",
  "move": "h3h2"
 },
 {
  "fen": "4r3/3k4/5Bb1/3p4/1P1n1P2/6PP/1R1K4/2R5 b - - 6 47",
  "move": "d4f3"
 },
 {
  "fen": "8/3QB3/7R/k2p4/2b4K/5r1P/2P3qP/8 w - - 4 46",
  "move": "d7a7"
 },
 {
  "fen": "3r2k1/5p2/7p/2p3p1/6P1/1PK2P1P/5q2/Q5R1 b - - 13 66",
  "move": "f2d2"
 },
 {
  "fen": "8/3k4/3B4/5R1p/2N4P/2P5/8/4R1K1 w - - 5 52",
  "move": "e1e7"
 },
 {
  "fen": "8/8/R7/p1P4k/P2P4/5P1P/6K1/8 w - - 11 66",
  "move": "f3f4"
 },
 {
  "fen": "8/8/6p1/1p5p/6qP/8/p1k5/5K2 b - - 3 64",
  "move": "a2a1q"
 },
 {
  "fen": "2b2b1k/1p6/p3p2p/P3Pp2/1Pq5/8/1K3Br1/8 b - - 5 66",
  "move": "g2f2"
 },
 {
  "fen": "2k4r/pp3bp1/2n4p/4p3/P4P1P/RnP5/1P4P1/1KBr2NR b - - 3 27",
  "move": "d1c1"
 },
 {
  "fen": "8/1p2k3/5p2/3n3P/P1pP4/2P5/K7/4q3 b - - 1 54",
  "move": "e1c1"
 },
 {
  "fen": "8/1p2k3/5p2/P2n3P/2pP4/2q5/K7/8 b - - 0 55",
  "move": "c3c1"
 },
 {
  "fen": "8/1p2k3/5p2/3n3P/2pP4/4q3/8/K7 b - - 9 60",
  "move": "e3c1"
 },
 {
  "fen": "2b2r2/p7/3k1p2/p5P1/Pn6/8/r4PPR/3BK1N1 b - - 2 32",
  "move": "b4d3"
 },
 {
  "fen": "rn1Q4/1R6/p6k/2p5/P3P3/3P1Pp1/7b/5K1R w - - 0 33",
  "move": "d8f6"
 },
 {
  "fen": "8/5p2/1p3k2/pP2pP1R/P3K2P/6R1/2r5/3q4 b - - 5 57",
  "move": "d1d4"
 },
 {
  "fen": "3B4/1R1P3k/p7/P4P2/1P2pK2/4p3/8/5B2 w - - 0 53",
  "move": "d8g5"
 },
 {
  "fen": "3r2k1/4R3/6p1/1p3p1p/5P1P/6K1/r7/6R1 b - - 0 41",
  "move": "d8d3"
 },
 {
  "fen": "8/8/5pp1/8/3QP3/4R3/7P/2k4K w - - 4 51",
  "move": "e3e2"
 },
 {
  "fen": "3r4/P1p2pp1/3bk3/3p3p/3P3P/2Pn1K2/3r2P1/8 b - - 0 41",
  "move": "d6f4"
 },
 {
  "fen": "7r/3k1pp1/b3p1p1/4P3/1b3P2/2n4P/r5P1/2B1K1NR b - - 7 28",
  "move": "c3e4"
 },
 {
  "fen": "r3r3/4b1kn/qp1p4/p1pPpQ2/P1P1P3/1PN4R/5P2/RK6 w - - 30 54",
  "move": "h3h7"
 },
 {
  "fen": "4kr2/1p4p1/2b1p3/1P6/3p1n1P/2N5/6pR/6K1 b - - 0 35",
  "move": "f4e2"
 },
 {
  "fen": "1k6/6P1/8/2PPR3/8/3K4/8/8 w - - 3 68",
  "move": "e5e7"
 },
 {
  "fen": "1k6/6P1/8/2PP1R2/3K4/8/8/8 w - - 7 70",
  "move": "f5f7"
 },
 {
  "fen": "2kr4/1b6/5p2/p3p2B/5r1P/2N4R/7K/6N1 b - - 0 51",
  "move": "f4f2"
 },
 {
  "fen": "2b1B2k/2p5/4pp2/5N2/3P4/r1n3RP/1R5q/2K5 b - - 4 48",
  "move": "a3a1"
 },
 {
  "fen": "6RR/k1p5/1p4p1/3P1p2/pqP5/5N2/r2N2PK/8 w - - 0 47",
  "move": "g8a8"
 }
];

export const MATE_IN_3: MatePuzzle[] = [];

export const TACTICS: TacticPuzzle[] = [
 {
  "fen": "2kr3r/2p2p2/p4p2/8/7p/2q2P1P/P7/R2Q1KNR b - - 1 20",
  "accept": [
   "d8d1"
  ],
  "gain": 472
 },
 {
  "fen": "1k1r4/2p5/4bp2/1P4p1/1R5P/7P/8/rNKR4 w - - 0 38",
  "accept": [
   "d1d8"
  ],
  "gain": 524
 },
 {
  "fen": "3rk1nr/p1p1p1bp/3qbpp1/3p4/1n1P1P2/N4N1P/PP1QP1P1/R1B1KB1R w KQk - 4 13",
  "accept": [
   "a3b5"
  ],
  "gain": 320
 },
 {
  "fen": "1rbk1b1r/1ppqpppp/2n2n2/pN1p4/3P1P2/3Q3P/PPP1P1PR/R1B1KBN1 b Q - 1 8",
  "accept": [
   "c6b4"
  ],
  "gain": 300
 },
 {
  "fen": "rn1qkbnr/3b4/p1p1p1pp/1p1pNp1Q/3P1B2/P1P1P1P1/1P1N1P1P/R3KB1R w KQkq - 0 11",
  "accept": [
   "h5g6"
  ],
  "gain": 467
 },
 {
  "fen": "2r4r/5kp1/4pp2/6P1/p6p/P2P4/1B4PP/2Q3K1 b - - 0 30",
  "accept": [
   "c8c1"
  ],
  "gain": 422
 },
 {
  "fen": "rnb1k1nr/2p3pp/4pp2/ppb2q2/3p1N2/P2P1N1P/1PP1PPP1/R1BQKB1R w KQkq - 1 10",
  "accept": [
   "g2g4"
  ],
  "gain": 381
 },
 {
  "fen": "1r6/5kp1/2r1bn2/1pb2n2/3p3p/3P3P/1QPBNPB1/6KR w - - 0 31",
  "accept": [
   "g2c6"
  ],
  "gain": 495
 },
 {
  "fen": "2r3k1/pp1p1p2/q4Bpp/2p5/PbP1P3/1P1r2P1/2QP1P1P/R4RK1 b - - 2 17",
  "accept": [
   "d3d2"
  ],
  "gain": 451
 },
 {
  "fen": "2r3k1/pp1p1p2/q4Bpp/2p5/PbP1P3/1P4P1/3r1P1P/R1Q2RK1 b - - 1 18",
  "accept": [
   "a6f6"
  ],
  "gain": 345
 },
 {
  "fen": "rn1qkb1r/2pp1pp1/1p2p1bp/p2n4/Q1PP3P/1P2BN2/P2NPPP1/R3KB1R b KQkq - 0 10",
  "accept": [
   "d5c3"
  ],
  "gain": 361
 },
 {
  "fen": "rn1qkb1r/2pp1pp1/1p2p1bp/p5B1/Q1PP3P/1Pn2N2/P2NPPP1/R3KB1R b KQkq - 2 11",
  "accept": [
   "h6g5"
  ],
  "gain": 744
 },
 {
  "fen": "r1b1r1k1/3n1p2/pp4p1/b3p2p/1pP1P2P/P4P2/3B1P1R/RN1K1B2 w - - 0 20",
  "accept": [
   "a3b4"
  ],
  "gain": 373
 },
 {
  "fen": "r1b1r1k1/3n1p2/pp4p1/4p2p/1bP1P2P/5P2/3B1P1R/RN1K1B2 w - - 0 21",
  "accept": [
   "d2b4"
  ],
  "gain": 369
 },
 {
  "fen": "6k1/2r2p2/1pb3pp/p7/PR4P1/7P/2P5/1K2R3 b - - 0 33",
  "accept": [
   "a5b4"
  ],
  "gain": 600
 },
 {
  "fen": "2R4k/3b4/4pn2/p2p1rp1/P2P3p/4PP1P/2K3B1/R7 b - - 0 39",
  "accept": [
   "d7c8"
  ],
  "gain": 474
 },
 {
  "fen": "rnbk2nr/pp1p2Np/1q3p2/2p1b3/P3P1Q1/2P1B3/1P3PPP/RN2KB1R b KQ - 0 12",
  "accept": [
   "b6b2"
  ],
  "gain": 407
 },
 {
  "fen": "rnbk2nr/pp1p3p/4Np2/2p1b3/P3P1Q1/2P1B3/1q3PPP/RN2KB1R b KQ - 1 13",
  "accept": [
   "d7e6"
  ],
  "gain": 349
 },
 {
  "fen": "1k6/5r1B/1p1b1r2/p1pP4/P1P2p1p/1P2nN1P/5PPR/1K1R4 b - - 0 41",
  "accept": [
   "e3d1"
  ],
  "gain": 509
 },
 {
  "fen": "8/2kB4/1p1b4/p1pP4/P1P4p/1P5P/5rp1/1KR5 b - - 0 50",
  "accept": [
   "f2f1"
  ],
  "gain": 704
 },
 {
  "fen": "1k5r/6p1/2p2p1n/1p1p3p/1b1PB3/2N4P/Pp6/1R2K1R1 b - - 0 29",
  "accept": [
   "b4c3"
  ],
  "gain": 638
 },
 {
  "fen": "3rkb2/1p3pp1/p4q2/2p1n3/4PP2/7b/PPPB1R2/RN1QKBr1 b Q - 0 20",
  "accept": [
   "f6h4"
  ],
  "gain": 380
 },
 {
  "fen": "3rkb2/1p3pp1/p7/2p5/2n1PP1q/8/PPPBQ3/RN1K1Rr1 b - - 2 23",
  "accept": [
   "g1f1"
  ],
  "gain": 574
 },
 {
  "fen": "3rkb2/1p3pp1/p7/2p5/4PP1q/4n3/PPPBK3/RN3Q2 b - - 2 25",
  "accept": [
   "e3f1"
  ],
  "gain": 709
 },
 {
  "fen": "4kbr1/1q6/pB1p1p2/1p2p1p1/1P3nP1/P6P/2PQ3R/1K3B2 b - - 3 37",
  "accept": [
   "b7b6"
  ],
  "gain": 360
 },
 {
  "fen": "8/5k2/1p2r1p1/2bQ4/3p1P2/3B4/1q6/3R2K1 w - - 3 45",
  "accept": [
   "d1e1"
  ],
  "gain": 486
 },
 {
  "fen": "r2qkb1r/ppp1p1pp/3pb3/1P1n1p2/P2Pn3/3QPN2/2PN1PPP/R1B1KB1R b KQkq - 1 9",
  "accept": [
   "d5b4"
  ],
  "gain": 418
 },
 {
  "fen": "r1q1kb1r/ppp1p1pp/3p4/1P3B2/P2P4/4PNP1/2P2P1P/R1B1K2R b KQkq - 0 14",
  "accept": [
   "c8f5"
  ],
  "gain": 463
 },
 {
  "fen": "r1b1k3/1p1p1p2/3b4/p1pPp2p/PnB3q1/3P4/1PP5/R2QK1NR b q - 5 21",
  "accept": [
   "g4g2"
  ],
  "gain": 457
 },
 {
  "fen": "3rkbn1/pQ1np1pr/1p2p3/1P1pP3/3P3p/5P1P/P1NB1qP1/R2K1B1R w - - 1 22",
  "accept": [
   "d2e1"
  ],
  "gain": 514
 },
 {
  "fen": "6k1/3p3r/6pp/5p2/P4P2/3b3P/1B6/3R2K1 w - - 0 32",
  "accept": [
   "d1d3"
  ],
  "gain": 334
 },
 {
  "fen": "4k2r/pq4bp/n4p2/R1prN1p1/8/1PP5/4QPPP/2B3KR b k - 0 26",
  "accept": [
   "d5e5"
  ],
  "gain": 315
 },
 {
  "fen": "3r2kr/p5b1/5p2/3n3p/1Q6/2P5/1B3PP1/6KR b - - 0 45",
  "accept": [
   "d5b4"
  ],
  "gain": 578
 },
 {
  "fen": "8/8/8/2p4K/P1P4R/1r1kn3/3B4/8 w - - 6 58",
  "accept": [
   "d2e3"
  ],
  "gain": 325
 },
 {
  "fen": "8/8/8/8/8/B2k2K1/7r/8 w - - 0 64",
  "accept": [
   "g3h2"
  ],
  "gain": 503
 },
 {
  "fen": "b2k2n1/2B5/5p1r/P4ppp/2p4P/4P1P1/4NK2/R7 b - - 0 36",
  "accept": [
   "d8c7"
  ],
  "gain": 342
 },
 {
  "fen": "2r5/8/5p2/4k2p/4P3/4N2K/8/2R5 b - - 0 64",
  "accept": [
   "c8c1"
  ],
  "gain": 520
 },
 {
  "fen": "rb4k1/1p3rp1/8/1Np4p/p1P3bP/QP2qB2/P5P1/3R1K1R b - - 1 27",
  "accept": [
   "f7f3"
  ],
  "gain": 413
 },
 {
  "fen": "rb4k1/1p4p1/8/1Np4p/p1P3bP/QP2qP2/P7/3R1K1R b - - 0 28",
  "accept": [
   "e3f3"
  ],
  "gain": 617
 },
 {
  "fen": "rb4k1/1p4p1/8/1Np4p/p1P3bP/QP3q2/P7/3R2KR b - - 1 29",
  "accept": [
   "f3d1"
  ],
  "gain": 997
 },
 {
  "fen": "r1bqkr2/n1pp1p1p/7R/pp3Bb1/2P1P1P1/2Q3P1/PP6/RN3KN1 b q - 1 19",
  "accept": [
   "g5h6"
  ],
  "gain": 401
 },
 {
  "fen": "rnb2rk1/1p1ppp2/2p2npb/p6p/Pq1P1P2/1PN1P2N/Q1PB2PP/2KR1B1R w - - 4 13",
  "accept": [
   "c3b5"
  ],
  "gain": 321
 },
 {
  "fen": "r1bqkb1r/1pp1pp1p/p1n2np1/3p4/P2P2P1/2NQ1P2/1PPBP2P/R3KBNR b KQkq - 3 8",
  "accept": [
   "c6b4"
  ],
  "gain": 551
 },
 {
  "fen": "r1bqkb1r/1pp2p1p/p1n1pnp1/3p2P1/P2P4/2NQ1P2/1PPBP2P/R3KBNR b KQkq - 0 9",
  "accept": [
   "c6b4"
  ],
  "gain": 374
 },
 {
  "fen": "8/8/Q1Pk4/8/1r1n4/2NP3r/Kp6/8 w - - 0 59",
  "accept": [
   "c6c7"
  ],
  "gain": 362
 },
 {
  "fen": "r1b2k2/p1p1n1B1/1p2p3/8/4PP1p/2N2N2/2n2KPP/7R b - - 0 27",
  "accept": [
   "f8g7"
  ],
  "gain": 213
 },
 {
  "fen": "r3k1r1/1p3p2/1n2q3/1P1p4/1QpPp2P/P1P1N1b1/1B6/1K1R1R2 b - - 2 36",
  "accept": [
   "g3d6"
  ],
  "gain": 455
 },
 {
  "fen": "r3k1r1/1p3p2/1n1bq3/1P1N4/1QpPp2P/P1P5/1B6/1K1R1R2 b - - 0 37",
  "accept": [
   "e6d5"
  ],
  "gain": 611
 },
 {
  "fen": "4r3/8/3k4/8/4R3/8/2pK4/8 w - - 0 53",
  "accept": [
   "e4e8"
  ],
  "gain": 516
 },
 {
  "fen": "r4bnr/3k3p/2p1p3/3pB3/p5P1/2N5/PPP3qP/R2QK2R w KQ - 5 18",
  "accept": [
   "h1f1"
  ],
  "gain": 300
 },
 {
  "fen": "8/5k2/8/8/4K3/1p4P1/8/8 b - - 1 48",
  "accept": [
   "b3b2"
  ],
  "gain": 750
 },
 {
  "fen": "r2qkb1r/1pp1pppp/p4n2/6B1/3n4/1P1B1N2/1PP2PPP/R2Q1RK1 w q - 2 12",
  "accept": [
   "f3d4"
  ],
  "gain": 298
 },
 {
  "fen": "8/1kb1R3/8/P7/1P6/8/8/1Kr5 w - - 0 66",
  "accept": [
   "b1c1"
  ],
  "gain": 506
 },
 {
  "fen": "3q1knr/1pp5/3p1p1p/r2Np3/2PnP1b1/b2P1N2/P1QB1PBP/3R1RK1 w - - 2 17",
  "accept": [
   "f3d4"
  ],
  "gain": 195
 },
 {
  "fen": "7r/p4pk1/1p2p3/6P1/Pn4Pp/R7/6PR/4K3 b - - 0 43",
  "accept": [
   "b4c2"
  ],
  "gain": 478
 },
 {
  "fen": "7r/p4pk1/1p2p3/6P1/P5Pp/R7/2n2KPR/8 b - - 2 44",
  "accept": [
   "c2a3"
  ],
  "gain": 494
 },
 {
  "fen": "8/p6R/1p5k/6p1/P5Pp/6P1/2n2K2/8 b - - 0 50",
  "accept": [
   "h6h7"
  ],
  "gain": 509
 },
 {
  "fen": "3k1b2/1p1q2p1/r2p1n2/p1p3Nr/P1P3pP/2N1R1P1/QP3P2/5K1R w - - 1 24",
  "accept": [
   "g5e6"
  ],
  "gain": 305
 },
 {
  "fen": "2k2b2/1p1q2p1/r2pNn2/p1p4r/P1P3pP/2N1R1P1/QP3P2/5K1R w - - 3 25",
  "accept": [
   "e6f8"
  ],
  "gain": 317
 },
 {
  "fen": "1Qbk3r/3p1p2/p5p1/1pN5/2P1P3/8/3q1P1P/6RK w - - 0 36",
  "accept": [
   "c5b7"
  ],
  "gain": 485
 },
 {
  "fen": "1Qb4r/1N1pkp2/p5p1/1p6/2P1P3/8/3q1P1P/6RK w - - 2 37",
  "accept": [
   "b8e5"
  ],
  "gain": 720
 },
 {
  "fen": "2b2k1r/1N1p1p2/p5p1/1p2Q3/2P1P3/8/3q1P1P/6RK w - - 4 38",
  "accept": [
   "e5h8"
  ],
  "gain": 736
 },
 {
  "fen": "4k2r/p1p2pp1/3bp3/r2p1b1p/3PPP1P/2P3n1/1PQ3P1/2B1KB1R b Kk - 0 21",
  "accept": [
   "f5e4"
  ],
  "gain": 474
 },
 {
  "fen": "2b1kb1r/3p1pp1/2B1p1p1/4P3/5P2/n6P/r2B2P1/1R3KNR b k - 0 23",
  "accept": [
   "a3b1"
  ],
  "gain": 783
 },
 {
  "fen": "r3kbnr/1pp2Npp/p1n5/2q5/4pPb1/1B6/PPPP2PP/RNBQK2R w KQkq - 2 9",
  "accept": [
   "d1g4"
  ],
  "gain": 720
 },
 {
  "fen": "r4b1N/1p4pp/pkn5/2p5/5PB1/P7/q2P2PP/RN2K2R w KQ - 0 22",
  "accept": [
   "a1a2"
  ],
  "gain": 871
 },
 {
  "fen": "8/2k5/p6b/1p6/2p1N3/P2P1r2/5K1P/3R4 w - - 0 44",
  "accept": [
   "f2f3"
  ],
  "gain": 516
 },
 {
  "fen": "4R3/2p5/2p2k2/3b4/6r1/2P3PP/1P6/6K1 w - - 0 40",
  "accept": [
   "h3g4"
  ],
  "gain": 423
 },
 {
  "fen": "2kr1r2/1qp2ppp/p3pn2/4P3/Q3bPP1/Pn2P3/1P1P1K1P/R1B2BR1 w - - 1 21",
  "accept": [
   "f1a6"
  ],
  "gain": 319
 },
 {
  "fen": "2r1k1r1/5p2/4p3/P4pPp/1QbP1P2/4P2K/1P1n3P/6R1 w - - 0 41",
  "accept": [
   "b4d2"
  ],
  "gain": 315
 },
 {
  "fen": "2b3k1/2p5/q3pp2/1p1n3r/r2P3p/P1n2N1P/Q2B2P1/3RKBR1 b - - 7 37",
  "accept": [
   "c3a2"
  ],
  "gain": 854
 }
];
