import type { Rng } from '@/utils/random';
import type { DifficultySetting } from '@/types';
import { drawFromBank } from '../_shared/quiz/engine';
import type { BankItem, QuizQuestion } from '../_shared/quiz/engine';

export const BANK: BankItem[] = [
  {
    prompt: 'Which planet is closest to the Sun?',
    correct: 'Mercury',
    wrong: ['Venus', 'Mars', 'Earth'],
    level: 1,
  },
  {
    prompt: 'Which planet is known as the Red Planet?',
    correct: 'Mars',
    wrong: ['Jupiter', 'Venus', 'Saturn'],
    level: 1,
  },
  {
    prompt: 'What is the largest planet in our solar system?',
    correct: 'Jupiter',
    wrong: ['Saturn', 'Neptune', 'Earth'],
    level: 1,
  },
  {
    prompt: 'What gas do plants take in from the air to make food?',
    correct: 'Carbon dioxide',
    wrong: ['Oxygen', 'Nitrogen', 'Hydrogen'],
    level: 1,
  },
  {
    prompt: 'What gas do humans need to breathe in to live?',
    correct: 'Oxygen',
    wrong: ['Carbon dioxide', 'Helium', 'Nitrogen'],
    level: 1,
  },
  {
    prompt: 'What is the chemical formula for water?',
    correct: 'H₂O',
    wrong: ['CO₂', 'O₂', 'H₂O₂'],
    level: 1,
  },
  {
    prompt: 'At what temperature does water boil at sea level?',
    correct: '100 °C',
    wrong: ['90 °C', '120 °C', '212 °C'],
    level: 1,
  },
  {
    prompt: 'At what temperature does water freeze?',
    correct: '0 °C',
    wrong: ['−10 °C', '4 °C', '32 °C'],
    level: 1,
  },
  {
    prompt: 'How many bones are in the adult human body?',
    correct: '206',
    wrong: ['186', '226', '306'],
    level: 2,
  },
  {
    prompt: 'Which organ pumps blood around the body?',
    correct: 'Heart',
    wrong: ['Lungs', 'Liver', 'Kidneys'],
    level: 1,
  },
  {
    prompt: 'What is the largest organ of the human body?',
    correct: 'Skin',
    wrong: ['Liver', 'Brain', 'Lungs'],
    level: 2,
  },
  {
    prompt: 'What force keeps us on the ground?',
    correct: 'Gravity',
    wrong: ['Magnetism', 'Friction', 'Inertia'],
    level: 1,
  },
  {
    prompt: 'What is the centre of an atom called?',
    correct: 'Nucleus',
    wrong: ['Electron', 'Proton', 'Orbit'],
    level: 2,
  },
  {
    prompt: 'Which particle has a negative charge?',
    correct: 'Electron',
    wrong: ['Proton', 'Neutron', 'Photon'],
    level: 2,
  },
  {
    prompt: 'What part of a plant makes food using sunlight?',
    correct: 'Leaves',
    wrong: ['Roots', 'Stem', 'Flowers'],
    level: 1,
  },
  {
    prompt: 'What is the process by which plants make food from sunlight?',
    correct: 'Photosynthesis',
    wrong: ['Respiration', 'Digestion', 'Evaporation'],
    level: 1,
  },
  {
    prompt: 'How long does it take Earth to orbit the Sun?',
    correct: 'About 365 days',
    wrong: ['About 30 days', 'About 24 hours', 'About 10 years'],
    level: 1,
  },
  {
    prompt: 'What is the speed of light in a vacuum, approximately?',
    correct: '300,000 km per second',
    wrong: ['300 km per second', '30,000 km per second', '3 million km per second'],
    level: 3,
  },
  {
    prompt: 'What type of animal is a whale?',
    correct: 'Mammal',
    wrong: ['Fish', 'Reptile', 'Amphibian'],
    level: 1,
  },
  {
    prompt: 'What do we call animals that eat only plants?',
    correct: 'Herbivores',
    wrong: ['Carnivores', 'Omnivores', 'Insectivores'],
    level: 1,
  },
  {
    prompt: 'What is the hardest natural substance?',
    correct: 'Diamond',
    wrong: ['Gold', 'Iron', 'Quartz'],
    level: 1,
  },
  {
    prompt: 'Which blood cells fight infection?',
    correct: 'White blood cells',
    wrong: ['Red blood cells', 'Platelets', 'Plasma'],
    level: 2,
  },
  {
    prompt: 'What carries oxygen in red blood cells?',
    correct: 'Haemoglobin',
    wrong: ['Insulin', 'Keratin', 'Collagen'],
    level: 3,
  },
  {
    prompt: 'What is the unit of electrical resistance?',
    correct: 'Ohm',
    wrong: ['Volt', 'Ampere', 'Watt'],
    level: 2,
  },
  {
    prompt: 'What is the unit of force?',
    correct: 'Newton',
    wrong: ['Joule', 'Pascal', 'Watt'],
    level: 2,
  },
  {
    prompt: 'Which scientist proposed the theory of general relativity?',
    correct: 'Albert Einstein',
    wrong: ['Isaac Newton', 'Niels Bohr', 'Galileo Galilei'],
    level: 1,
  },
  {
    prompt: 'Who is known for the laws of motion and universal gravitation?',
    correct: 'Isaac Newton',
    wrong: ['Albert Einstein', 'Charles Darwin', 'Nikola Tesla'],
    level: 1,
  },
  {
    prompt: 'Who proposed evolution by natural selection?',
    correct: 'Charles Darwin',
    wrong: ['Gregor Mendel', 'Louis Pasteur', 'Carl Linnaeus'],
    level: 2,
  },
  {
    prompt: 'What is the most abundant gas in Earth’s atmosphere?',
    correct: 'Nitrogen',
    wrong: ['Oxygen', 'Carbon dioxide', 'Argon'],
    level: 2,
  },
  {
    prompt: 'What is the pH of pure water at 25 °C?',
    correct: '7',
    wrong: ['0', '5', '14'],
    level: 2,
  },
  {
    prompt: 'Which planet has the most prominent rings?',
    correct: 'Saturn',
    wrong: ['Jupiter', 'Uranus', 'Neptune'],
    level: 1,
  },
  {
    prompt: 'What is the closest star to Earth?',
    correct: 'The Sun',
    wrong: ['Proxima Centauri', 'Sirius', 'Polaris'],
    level: 1,
  },
  {
    prompt: 'Which part of the cell contains DNA in plants and animals?',
    correct: 'Nucleus',
    wrong: ['Cell membrane', 'Ribosome', 'Cytoplasm'],
    level: 2,
  },
  {
    prompt: 'What is the powerhouse of the cell?',
    correct: 'Mitochondrion',
    wrong: ['Nucleus', 'Chloroplast', 'Golgi apparatus'],
    level: 2,
  },
  {
    prompt: 'What kind of energy is stored in a stretched rubber band?',
    correct: 'Elastic potential energy',
    wrong: ['Kinetic energy', 'Thermal energy', 'Nuclear energy'],
    level: 3,
  },
  {
    prompt: 'Sound travels fastest through which of these?',
    correct: 'Steel',
    wrong: ['Air', 'Water', 'A vacuum'],
    level: 3,
    explain: 'Sound cannot travel through a vacuum at all.',
  },
  {
    prompt: 'What causes the seasons on Earth?',
    correct: 'The tilt of Earth’s axis',
    wrong: ['Earth’s distance from the Sun', 'The Moon’s orbit', 'Solar flares'],
    level: 3,
  },
  {
    prompt: 'What is the boiling point of water in Fahrenheit?',
    correct: '212 °F',
    wrong: ['100 °F', '180 °F', '32 °F'],
    level: 2,
  },
  {
    prompt: 'Which vitamin does your skin make in sunlight?',
    correct: 'Vitamin D',
    wrong: ['Vitamin C', 'Vitamin A', 'Vitamin B12'],
    level: 2,
  },
  {
    prompt: 'What is the study of earthquakes called?',
    correct: 'Seismology',
    wrong: ['Meteorology', 'Geology', 'Volcanology'],
    level: 3,
  },
  {
    prompt: 'What type of rock forms from cooled lava?',
    correct: 'Igneous',
    wrong: ['Sedimentary', 'Metamorphic', 'Limestone'],
    level: 2,
  },
  {
    prompt: 'Which planet spins on its side?',
    correct: 'Uranus',
    wrong: ['Neptune', 'Venus', 'Mars'],
    level: 3,
  },
  {
    prompt: 'Which is the hottest planet in our solar system?',
    correct: 'Venus',
    wrong: ['Mercury', 'Mars', 'Jupiter'],
    level: 2,
    explain: 'Its thick atmosphere traps heat, making it hotter than Mercury.',
  },
  {
    prompt: 'What is a group of stars forming a recognisable pattern called?',
    correct: 'Constellation',
    wrong: ['Galaxy', 'Nebula', 'Comet'],
    level: 1,
  },
  {
    prompt: 'How many chambers does the human heart have?',
    correct: '4',
    wrong: ['2', '3', '6'],
    level: 2,
  },
  {
    prompt: 'What does a thermometer measure?',
    correct: 'Temperature',
    wrong: ['Pressure', 'Humidity', 'Wind speed'],
    level: 1,
  },
  {
    prompt: 'What is the main gas in the Sun?',
    correct: 'Hydrogen',
    wrong: ['Helium', 'Oxygen', 'Carbon'],
    level: 2,
  },
  {
    prompt: 'What is absolute zero on the Celsius scale?',
    correct: '−273.15 °C',
    wrong: ['−100 °C', '−459.67 °C', '0 °C'],
    level: 3,
  },
];

export const makeQuestions = (rng: Rng, d: DifficultySetting): QuizQuestion[] =>
  drawFromBank(BANK, rng, d, 10);
