/** Common English idioms, proverbs and everyday phrases, with a category hint. */
export const PHRASES: [category: string, phrase: string, level: 1 | 2 | 3][] = [
  ['Phrase', 'PIECE OF CAKE', 1],
  ['Phrase', 'BREAK THE ICE', 1],
  ['Phrase', 'ONCE IN A BLUE MOON', 1],
  ['Phrase', 'UNDER THE WEATHER', 1],
  ['Phrase', 'HIT THE ROAD', 1],
  ['Phrase', 'BETTER LATE THAN NEVER', 1],
  ['Phrase', 'TIME FLIES', 1],
  ['Phrase', 'CALL IT A DAY', 1],
  ['Phrase', 'SPILL THE BEANS', 1],
  ['Phrase', 'LET THE CAT OUT OF THE BAG', 2],
  ['Phrase', 'BITE THE BULLET', 2],
  ['Phrase', 'COST AN ARM AND A LEG', 2],
  ['Phrase', 'BACK TO SQUARE ONE', 2],
  ['Phrase', 'THE BALL IS IN YOUR COURT', 2],
  ['Phrase', 'ON CLOUD NINE', 1],
  ['Phrase', 'BURN THE MIDNIGHT OIL', 2],
  ['Phrase', 'HIT THE NAIL ON THE HEAD', 2],
  ['Phrase', 'PULL SOMEBODY’S LEG', 2],
  ['Phrase', 'SLEEP ON IT', 1],
  ['Phrase', 'WHEN PIGS FLY', 1],
  ['Phrase', 'THE BEST OF BOTH WORLDS', 2],
  ['Phrase', 'A BLESSING IN DISGUISE', 3],
  ['Phrase', 'BEAT AROUND THE BUSH', 2],
  ['Phrase', 'CUT CORNERS', 1],
  ['Phrase', 'GO BACK TO THE DRAWING BOARD', 3],
  ['Phrase', 'ADD INSULT TO INJURY', 3],
  ['Phrase', 'MISS THE BOAT', 1],
  ['Phrase', 'ON THE FENCE', 1],
  ['Phrase', 'THROUGH THICK AND THIN', 2],
  ['Phrase', 'UP IN THE AIR', 1],
  ['Proverb', 'PRACTICE MAKES PERFECT', 1],
  ['Proverb', 'ACTIONS SPEAK LOUDER THAN WORDS', 2],
  ['Proverb', 'THE EARLY BIRD CATCHES THE WORM', 2],
  ['Proverb', 'LOOK BEFORE YOU LEAP', 1],
  ['Proverb', 'TWO HEADS ARE BETTER THAN ONE', 2],
  ['Proverb', 'EVERY CLOUD HAS A SILVER LINING', 2],
  ['Proverb', 'HONESTY IS THE BEST POLICY', 2],
  ['Proverb', 'WHERE THERE IS A WILL THERE IS A WAY', 3],
  ['Proverb', 'ROME WAS NOT BUILT IN A DAY', 2],
  ['Proverb', 'DO NOT JUDGE A BOOK BY ITS COVER', 2],
  ['Proverb', 'SLOW AND STEADY WINS THE RACE', 2],
  ['Proverb', 'THE PEN IS MIGHTIER THAN THE SWORD', 3],
  ['Proverb', 'KNOWLEDGE IS POWER', 1],
  ['Proverb', 'NO PAIN NO GAIN', 1],
  ['Proverb', 'A PICTURE IS WORTH A THOUSAND WORDS', 3],
  ['Proverb', 'ALL THAT GLITTERS IS NOT GOLD', 3],
  ['Proverb', 'BIRDS OF A FEATHER FLOCK TOGETHER', 3],
  ['Proverb', 'CURIOSITY KILLED THE CAT', 2],
  ['Proverb', 'HOME IS WHERE THE HEART IS', 2],
  ['Proverb', 'LAUGHTER IS THE BEST MEDICINE', 2],
  ['Proverb', 'AN APPLE A DAY KEEPS THE DOCTOR AWAY', 3],
  ['Proverb', 'WHAT GOES AROUND COMES AROUND', 2],
  ['Proverb', 'PATIENCE IS A VIRTUE', 2],
  ['Proverb', 'TIME IS MONEY', 1],
  ['Food & Drink', 'PEANUT BUTTER AND JELLY', 2],
  ['Food & Drink', 'FISH AND CHIPS', 1],
  ['Food & Drink', 'HOT CHOCOLATE', 1],
  ['Food & Drink', 'CHOCOLATE CHIP COOKIES', 2],
  ['Food & Drink', 'SPAGHETTI AND MEATBALLS', 2],
  ['Food & Drink', 'APPLE PIE', 1],
  ['Food & Drink', 'SCRAMBLED EGGS ON TOAST', 2],
  ['Food & Drink', 'FRESHLY SQUEEZED ORANGE JUICE', 3],
  ['Place', 'THE GREAT WALL OF CHINA', 2],
  ['Place', 'THE SAHARA DESERT', 1],
  ['Place', 'THE PACIFIC OCEAN', 1],
  ['Place', 'THE AMAZON RAINFOREST', 2],
  ['Place', 'THE GRAND CANYON', 1],
  ['Place', 'MOUNT EVEREST', 1],
  ['Place', 'THE NORTH POLE', 1],
  ['Place', 'THE MILKY WAY', 1],
  ['Thing', 'A CUP OF TEA', 1],
  ['Thing', 'A PAIR OF SUNGLASSES', 2],
  ['Thing', 'A HOT AIR BALLOON', 2],
  ['Thing', 'A ROLLER COASTER', 2],
  ['Thing', 'A MESSAGE IN A BOTTLE', 2],
  ['Thing', 'A TREASURE MAP', 1],
  ['Thing', 'THE REMOTE CONTROL', 2],
  ['Thing', 'A SPARE TYRE', 2],
  ['Activity', 'BUILDING A SANDCASTLE', 2],
  ['Activity', 'FLYING A KITE', 1],
  ['Activity', 'WATCHING THE SUNSET', 2],
  ['Activity', 'GOING FOR A WALK', 1],
  ['Activity', 'PLAYING HIDE AND SEEK', 2],
  ['Activity', 'SINGING IN THE RAIN', 2],
  ['Activity', 'RIDING A BICYCLE', 2],
  ['Activity', 'STARGAZING AT MIDNIGHT', 3],
];
