import type { AchievementDefinition } from '@/types';

export const achievements: AchievementDefinition[] = [
  {
    id: 'mines.first-clear',
    gameId: 'minesweeper',
    name: 'All Clear',
    description: 'Clear your first board.',
    target: 1,
    icon: '💣',
    coins: 15,
  },
  {
    id: 'mines.clear-normal',
    gameId: 'minesweeper',
    name: 'Steady Hands',
    description: 'Clear a Normal board.',
    target: 1,
    icon: '🧤',
    coins: 30,
  },
  {
    id: 'mines.clear-hard',
    gameId: 'minesweeper',
    name: 'Bomb Squad',
    description: 'Clear a Hard board.',
    target: 1,
    icon: '🎖️',
    coins: 60,
  },
  {
    id: 'mines.fast-easy',
    gameId: 'minesweeper',
    name: 'Under a Minute',
    description: 'Clear an Easy board in under 60 seconds.',
    target: 1,
    icon: '⏱️',
    coins: 25,
  },
  {
    id: 'mines.no-flags',
    gameId: 'minesweeper',
    name: 'Flagless',
    description: 'Clear any board without placing a flag.',
    target: 1,
    icon: '🚩',
    coins: 40,
  },
  {
    id: 'mines.chord',
    gameId: 'minesweeper',
    name: 'Chord Master',
    description: 'Use the chord shortcut 20 times.',
    target: 20,
    icon: '🎹',
    coins: 20,
  },
];
